### ISSUE TITLE
Trouble if you deploy with an existing connection open in the browser

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#101]
If you republish a tutorial while an existing connection to the tutorial is open in the browser, the new tutorial will appear not to work. Specifically, the progress indicators and continue buttons will not function. If you close the previously open connection to the tutorial, the new connection will immediately restore status and begin to work. In either case, if you close all connections and then re-open the tutorial, it will work. In other words, the deployment is ultimately successful but will seem buggy if you do not probe deeper.

I'm not sure that this is an issue that requires any development work, but it took me quite a long time to figure out what was going on - so I wanted to get the word out.

I noticed this phenomenon on Google Chrome and have reproduced it several times. It may be limited to tutorials that use progressive reveal.

**Comment by schloerke** [comment]
I believe this was fixed in https://github.com/rstudio/learnr/pull/305. Closing
