### ISSUE TITLE
Ability to parse solution-code or check-code as an actual numeric or character, not the code to get it

### ISSUE THREAD

**Issue by gsimchoni** [rstudio/learnr#104]
Suppose I want the user to tell me, and I don't care how she gets it, what is "the mean of the 3rd column" in a given `data.frame`:

    What is the mean of the 3rd column in df?
    ```{r q1, exercise = TRUE, exercise.eval = FALSE, exercise.lines = 1}

    ```

    ```{r q1-solution}
    mean(df[, 3])
    ```

    ```{r q1-check}
    mean(df[, 3])
    ```

In this scenario, the only correct answer is `mean(df[, 3])`, but there are many ways to get there, and I want the correct answer to be simply the actual number, say `3.5`.

Currently I can't do that without writing in the solution explicitly `3.5`, and this becomes an issue say if the data.frame `df` (or any other object I'm asking about) was created dynamically, e.g. by sampling, and I can't hard-code it.

**Comment by jjallaire** [comment]
The idea is that you use a code checking package like checkr (https://github.com/dtkaplan/checkr) which provides higher level tools for doing this. @dtkaplan

**Comment by gsimchoni** [comment]
I really wanted to use checkr, the `same_num` function sounds like what I want, however I didn't understand from its help page how to use it, couldn't find any examples with a simple google search, so I solved the problem by customizing my checker function:

```
is_bad_code <- function(user_code, check_code, envir_result) {
  eval(parse(text = user_code)) != eval(parse(text = check_code), envir = envir_result)
}

checker <- function(label, user_code, check_code, envir_result, evaluate_result, ...) {
  if (is_bad_code(user_code, check_code, envir_result)) {
    return(list(message = "Code wasn't right!", correct = FALSE, location = "append"))
  } else {
    return(list(message = "Great Job!", correct = TRUE, location = "append"))
  }
}  
```

For me the issue is closed, thanks.
