### ISSUE TITLE
Browser Frozen While Code Running

### ISSUE THREAD

**Issue by DarioS** [rstudio/learnr#105]
When code is running and the progress circle is spinning, the browser GUI freezes until the results are returned. It's apparent when using the examples on shinyapps.io. I am using Firefox version 54 on Debian version 8.8. Being implemented in JavaScript, there's not much hope of avoiding this.

**Comment by jjallaire** [comment]
Yes, the idea is that exercises shouldn't be very long running in the first
place (to provide quick feedback to students). Of course, sometimes it's
unavoidable and in those cases the progress experience is indeed not the
best.
