### ISSUE TITLE
Collapsible exercises/subsections?

### ISSUE THREAD

**Issue by cpsievert** [rstudio/learnr#106]
I'm a big fan of how bookdown does this:

![collapse](https://user-images.githubusercontent.com/1365941/28581205-4adca6d8-7127-11e7-9d4f-9c15f3516ac1.gif)

I can think of two benefits:
  * Better UI for skipping to a subsection/exercise of interest (in a large section with many exercises).
  *  Could be helpful for users to remember/know what topics were/are covered in a given section.

**Comment by jjallaire** [comment]
@robbyshaver Do you agree and how easy would it be to add this?

**Comment by robbyshaver** [comment]
I think it would be a nice option. One level would probably be pretty easy to add, since we already track progress within a section - not sure what it would take to allow for additional levels...

**Comment by katiepress** [comment]
This would be great to have, especially for longer tutorials. I would take even one level! The tutorials I am working on are meant to be completed at the user's own pace, so it would be nice for them to be able to look through that sidebar for a topic they are particularly interested in working on.

**Comment by braunsb** [comment]
I use learnr on a daily basis and would love an alternative to the attached toc style. I want at least 4 levels to show up in the toc. It's driving me nuts. 🔩

**Comment by quantitative-ecologist** [comment]
Good day,

I was wondering if there were any advancements with this issue? It would really be awesome if this feature was available. Thank you very much!

**Comment by gadenbuie** [comment]
This is a great idea but it's not currently on the roadmap. Rather than give false hope, I'm going to close this issue. I've labelled it so we can find it again.

**Comment by MeikeSteinhilber** [comment]
Is there a workaround for this problem?
I need to create long tutorials and it will be difficult with only one level of headings. Either one topic is too full and it is difficult to get an overview or I have a huge amount of topics in the sidebar. Both options are not very user-friendly.
Maybe at the top of every section is a table of contents, containing only the sub-sections of this section? So it is not in the sidebar, but at least accessible.
Do you have a link or something? I have no idea how to set this up properly.
Many thanks in advance! 🙏🙏🙏
