### ISSUE TITLE
Translation of button captions to other languages

### ISSUE THREAD

**Issue by ilkerarslan** [rstudio/learnr#108]
I am trying to prepare R tutorials in Turkish but I couldn't find a way to translate button captions like ""Run Code", "Solution", "Start Over" etc.  I believe it would be great if there was a way to customize these labels.

**Comment by HeidiSeibold** [comment]
I'd be interested in that, too :+1:

**Comment by takewiki** [comment]
+1

**Comment by takewiki** [comment]
@ilkerarslan @HeidiSeibold  I have solved this problem by modifying the file:
learnr -->inst-->lib-->tutorial-->tutorial.js
1)change  caption for Run Code button:
  original code (near line 901 )
` var run_button = add_submit_button("fa-play", "btn-success", "Run Code", false);`
  modified one :
' var run_button = add_submit_button("fa-play", "btn-success", "your_caption_text_here1", false);'
2) change caption for Solution/Hint buttion
 original code (near line 1135)
`var button = addHintButton(caption);`
modified one
`  var button = addHintButton('your_caption_text_here2');`
3)change caption for Start Over
original code (near line 1067)
`var startOverButton = addHelperButton("fa-refresh", "Start Over");`
modified one
'var startOverButton = addHelperButton("fa-refresh", "your_caption_text_here3");'

the final result for buttion caption translated into chinese   as follow:
[buttion_caption_in_chinese](http://www.takewiki.com/wikipublic/images/f/f1/Learnr_github.png)

**Comment by cacsfre** [comment]
Great! but is there a right way to get this working on a per project basis ?

**Comment by gadenbuie** [comment]
Support for internationalization was added in #456 with help from @ColinFay!

We currently provide English and French translations and would happily accept translations for other languages as well. If you would like to contribute a translation for your native language, please read `vignette("multilang", package = "learnr")` for instructions, or submit a PR modifying [i18n_translations()](https://github.com/rstudio/learnr/blob/6694842d8b9a74fbff92ef8a64a49adcc5a30199/R/i18n.R#L124-L146) following the example for English.
