### ISSUE TITLE
Fonts in different languages

### ISSUE THREAD

**Issue by ilkerarslan** [rstudio/learnr#109]
I am trying to prepare R tutorials in my own language (Turkish). There are some letters in Turkish like: ş, ğ, ü, ö, ç, ı, Ş, İ, Ğ, Ü, Ö, Ç.

I couldn't find a way to print these letters in learnr. I was able to solve this issue in tufte package by using "main-font: UTF-8". Could it be possible for learnr also?

**Comment by schloerke** [comment]
@ilkerarslan Are you referring to quiz questions? If so, this will be addressed soon.
