### ISSUE TITLE
Rstudio won't knit once library(learnr) is in file 

### ISSUE THREAD

**Issue by newystats** [rstudio/learnr#113]
Rstudio v1.0.143 
R v3.4.0
OS X 10.11.6

.Rmd file:

---
title: "bug"
author: "Robert A.R. King"
date: "8/22/2017"
output: html_document
---

```{r setup, include=FALSE}
library(learnr)
```

## This fails

If I replace learnr with another package - no problem 

Markdown output

processing file: bug.Rmd
  |......................                                           |  33%
  ordinary text without R code

  |...........................................                      |  67%
label: setup (with options) 
List of 1
 $ include: logi FALSE

Quitting from lines 9-10 (bug.Rmd) 
Error: package or namespace load failed for 'learnr':
 .onAttach failed in attachNamespace() for 'learnr', details:
  call: rmarkdown::shiny_prerendered_chunk("server", sprintf("learnr:::register_http_handlers(session, metadata = %s)", 
  error: The shiny_prerendered_chunk function can only be called from within runtime: shiny_prerenered
Execution halted

**Comment by jjallaire** [comment]
You need to add `runtime: shiny_prerendered` to the document YAML (see the docs and examples at: https://rstudio.github.io/learnr/)

**Comment by newystats** [comment]
Thanks!
