### ISSUE TITLE
Refreshing/restarting the work in tutorial

### ISSUE THREAD

**Issue by nlhuong** [rstudio/learnr#123]
Hi,

I have written a package for storing all the learnr tutorials.

It is not clear to me how/where learnr is saving the progress on the work a user has made
in the tutorial. I would like to allow the user to restart/refresh the tutorial and discard all the progress
made. The issue is that whenever I run
learnr::run_tutorial("tutorial", package = "mypackage")
for the second/third, etc. times all the answers from the first session are stored, and 
I don't know how to refresh the session.

Please let me know how refreshing can be achieved.

Best,
Lan

**Comment by jjallaire** [comment]
Progress is saved in the platform-specific "scratch" storage area for applications (see https://github.com/r-lib/rappdirs for details).

Note that if you are using the `learnr::tutorial` R Markdown format (that's the default) then there is a "Start Over" button just below the floating table of contents on the left. See docs here: https://rstudio.github.io/learnr/formats.html#tutorial_format

**Comment by nlhuong** [comment]
Thank you for clarification.
