### ISSUE TITLE
setup Error: Your code ran longer than the permitted time limit for this exercise.

### ISSUE THREAD

**Issue by HeidiSeibold** [rstudio/learnr#124]
For an exercise I use data that is stored on GitHub. The problem is that it takes very long to load the data and the I get an error.
```
Error: Your code ran longer than the permitted time limit for this exercise.
```

My question: why is the setup chunk only run when the exercise chunk is used. Couldn't it be run before? That would also make it easier to use one setup chunk for several exercise chunks.

This is a reproducible example that shows my problem:
https://gist.github.com/HeidiSeibold/874d64b88850f84eb1eb799144c08895

**Comment by jjallaire** [comment]
For this use case I would suggest using a global setup or even global data chunk (in the latter case the download would be done only once when you render the Rmd and would then be cached for use by students). See details here: http://rmarkdown.rstudio.com/authoring_shiny_prerendered.html#additional_contexts.

**Comment by HeidiSeibold** [comment]
Thanks! I have the data in the R package containing the tutorial now. That is much faster and with the global data chunk it work well.
