### ISSUE TITLE
setup: error when two exercise chunks depend on one setup chunk

### ISSUE THREAD

**Issue by HeidiSeibold** [rstudio/learnr#125]
I have a setup chunk that reads the data. Then I have two exercise chunks where students should look at the data using the `names()` function. I get the following error:

![image](https://user-images.githubusercontent.com/14146757/31859212-d87900b4-b708-11e7-8ad1-344d3af1ae9c.png)

This seems to imply that setup chunks can only be used for one exercise. Is that the case?

The reproducible example can be found here:
https://gist.github.com/HeidiSeibold/b289d7be6904914ecf8ec5f331917eeb

(FYI it is almost the same as in #124)

**Comment by HeidiSeibold** [comment]
Please help me :pray: 

This is totally blocking the project I am working on.

Let me know if there is anything I can do to help.

**Comment by jjallaire** [comment]
The problem is that you are attempting to reference the "demographics1.xlsx" file before it's actually been downloaded (note that the download happens in the subsequent chunk). This may have worked for you locally in situations where the download had already occurred but it will always fail on a new workstation due to not doing the download before referencing the file.

I would also in-general recommend doing downloads, etc. in the global setup chunk because then they can occur once during compilation of the tutorial rather than for every student evaluating exercises.

**Comment by HeidiSeibold** [comment]
@jjallaire no that is not the problem. I updated the gist to make it more clear.

The problem only occurs for the second exercise ex_look2. When I comment it out, it does not happen. It also runs fine if I comment out the first exercise. See below:

### Does not work:
![image](https://user-images.githubusercontent.com/14146757/33230930-c011f036-d1ec-11e7-8c36-642a02528e8c.png)

### Works:
![image](https://user-images.githubusercontent.com/14146757/33230936-d4bfa744-d1ec-11e7-9c29-8cd162b997c6.png)

### Works:
![image](https://user-images.githubusercontent.com/14146757/33230945-f28f0ee0-d1ec-11e7-90e9-1d9905db7e56.png)

**Comment by jjallaire** [comment]
Okay, the issue appears to be that if you have a chunk with no content at all the solution chunk doesn't get picked up. Try this:

    ```{r ex_look2, exercise=TRUE}
    
    ```

i.e. just include a blank line in `ex_look2`

**Comment by HeidiSeibold** [comment]
Yes, that's right. :+1: 

What I do now is work without solutions (see [here](https://github.com/school-of-data/r-consortium-proposal/blame/master/r-package/inst/tutorials/en-introduction/en-introduction.Rmd#L304)). For the moment that is fine, but not optimal.

Do you think you'll be able to fix it?

**Comment by jjallaire** [comment]
For me just including the blank line in `ex_look2` fixes the problem. Are you saying that you can't include the blank line for some reason?

**Comment by HeidiSeibold** [comment]
Ah sorry, I didn't quite get what you were saying. Adding a blank line solves the problem.

Thank you so much! :tulip:

**Comment by jjallaire** [comment]
Great, glad we figured that out!
