### ISSUE TITLE
Adding hyperlinks to incorrect message

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/learnr#136]
It's possible to add a hyperlink to the message displayed when an incorrect choice is selected for a multiple choice question, e.g.

```r
question("What number is the letter A in the alphabet?",
         answer("8", message = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again."),
         answer("14"),
         answer("1", correct = TRUE),
         answer("23"), 
         allow_retry = TRUE
         )
```

However in most cases I'd like to display the same incorrect message for all wrong answers, so would like to be able to do something like the following.

```r
question("What number is the letter A in the alphabet?",
         answer("8"),
         answer("14"),
         answer("1", correct = TRUE),
         answer("23"), 
         incorrect = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again.",
         allow_retry = TRUE
         )
```

This doesn't give an error however the hyperlink does not work. I think it would be a nice feature to add. The current alternative is the following, which requires repeating the message for each option.

```r
question("What number is the letter A in the alphabet?",
         answer("8", message = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again."),
         answer("14", message = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again."),
         answer("1", correct = TRUE),
         answer("23", message = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again."), 
         allow_retry = TRUE
         )
```

**Comment by jjallaire** [comment]
You could write an R function that automates the repetitive message:

```r
alphabet_answer <- function(x) {
  answer(x, message = "See [here](https://en.wikipedia.org/wiki/English_alphabet) and try again.")
}
```

**Comment by mine-cetinkaya-rundel** [comment]
@jjallaire Sure, that's a good workaround too. I think it might be nice to have it built into the `incorrect` argument since it's already there for this purpose but doesn't allow for hyperlinks.

**Comment by jjallaire** [comment]
Yes, you are right that it's an oversight to now allow HTML for `incorrect`. We will fix that!

**Comment by mine-cetinkaya-rundel** [comment]
Great, thanks @jjallaire. Once that's in I can do a PR to the help file indicating this feature is available for these messages. Being able to point directly to resources is a nice feature.
