### ISSUE TITLE
for loops highlighted by code checker

### ISSUE THREAD

**Issue by kieranjmartin** [rstudio/learnr#141]
This is using learnr 0.9.1 and R 3.4.

When creating an exercise chunk, if I add a for loop, e.g.

    for (i in seq(1,5)){
         x <- i
     }

Then the code checking in the html highlights the for loop as an error , with "unexpected symbol 'in'" and "unexpected symbol 'seq'". The code seems to run fine when I used run code or submit answer so this is just affecting the display. I attach an example of this
![for_error](https://user-images.githubusercontent.com/15383022/36477197-39da6862-16f8-11e8-8c5e-26fe76d252e8.png)

**Comment by kevinushey** [comment]
Thanks for the bug report! Fixed up here:

https://github.com/rstudio/learnr/commit/2adadb607f58d4b25b51fc81655ca96428f9d723
https://github.com/rstudio/learnr/commit/7a6a5ae5be9d94820d1211262ccfd798c51006e5
