### ISSUE TITLE
Provide Explicit Instructions for Shiny Server Deployment

### ISSUE THREAD

**Issue by DarioS** [rstudio/learnr#142]
The Shiny Server section of the Publishing documentation doesn't explain how to publish a tutorial. I uploaded a tutorial folder to the same location as other folders with ordinary Shiny applications are in. I was surprised when I couldn't access the tutorial by the HTTP URL ending in tutorial.**html** but it does work if the URL ends in tutorial.**Rmd** I would intuitively expect the HTML file should be used but there's no information about the tutorial folder structure in the section of the documentation I refer to or whether the Rmd file should be converted to HTML. Another colleague gave up on getting his tutorial to work via Shiny Server and ended up making an R package for it instead.

The Rmd file header is:
```
---
title: "Investigating Combinations of Variables"
output: learnr::tutorial
runtime: shiny_prerendered
---
```

**Comment by jjallaire** [comment]
@bborgesr Could you follow up on enhancing the documentation here?

@trestletech Where in the Shiny Server documentation should we refer to that describes Rmd app deployment more clearly?

**Comment by trestletech** [comment]
Hi @DarioS . Sorry for the confusion. We do have a short section on this behavior in the admin guide: http://docs.rstudio.com/shiny-server/#r-markdown 

If you still have open questions after reading that section, please do let us know and we'll see how we can enhance the docs.

**Comment by DarioS** [comment]
That explains it. I wonder if a sentence could be added to the Deployment information on the learnr website, though. The Shiny Server administrator's manual isn't the most intuitive place to find such information.

**Comment by bborgesr** [comment]
@DarioS, is all the information you'd like to see in the learnr website contained in the link that @trestletech posted: http://docs.rstudio.com/shiny-server/#r-markdown ? If so, I can add that section relatively quickly to our website

**Comment by DarioS** [comment]
Yes, the last two paragraphs explain it clearly.

**Comment by bborgesr** [comment]
Closed by https://github.com/rstudio/learnr/commit/4805f86f23fbca80ef8bf4cfac39c321ffefd0f3.
