### ISSUE TITLE
Highlighting not picked up?

### ISSUE THREAD

**Issue by TryingToGetThere** [rstudio/learnr#150]
Hi,

I'm trying to get the SQL highlighting to work as follows:

output: 
  learnr::tutorial:
    theme: united
    highlight: pygments
runtime: shiny_prerendered

But the output gives: --no-highlight

Should I do it differently?

**Comment by TryingToGetThere** [comment]
output: 
  learnr::tutorial:
    theme: united
    highlight: pygments
runtime: shiny_prerendered

(with indents)

**Comment by garrettgman** [comment]
I'm running into the same problem: learnr doesn't apply syntax highlighting. If it did, I could use code commenting to emphasize some lines, while "fading out" others. This would be very useful!

**Comment by TryingToGetThere** [comment]
Hi - it took a while, but finally found a work around that works for me. The source hook is described here: https://curtisalexander.github.io/rmarkdown-syntax-highlighting/ Hope that helps anyone struggling with the same at the moment.

**Comment by schloerke** [comment]
Standard syntax highlighting is now back.  (master branch)

Alternative color schemes for code and exercise area are now enabled.  Code highlighting is enabled with the `highlight`. Exercise area (ace editor) theming is done iwth `ace_theme`.

```yaml
output:
  learnr::tutorial:
    highlight: pygments
    ace_theme: monokai
runtime: shiny_prerendered
```

**Comment by mpfp** [comment]
It's not working for me using the header info provided by @schloerke.  Do I have have the highlight program installed (as referenced in the link provided by @TryingToGetThere?

**Comment by lrdegeest** [comment]
Also not working for me. Working with the latest version of `learnr`
