### ISSUE TITLE
pandoc warning during exercise knit

### ISSUE THREAD

**Issue by jjallaire** [rstudio/learnr#154]
I am seeing this when running exercises:

```r
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'exercise.knit.utf8'
```

We render exercises using a couple of passes here:

https://github.com/rstudio/learnr/blob/master/R/exercise.R#L199-L244

@yihui Can you recommend the right workaround to suppress this warning? (or do I recall a recent commit to rmarkdown that would get rid of it globally?)

**Comment by yihui** [comment]
Adding `pandoc_args = c("--metadata", "pagetitle=PREVIEW"))` to `html_fragment()` here should fix it: 
https://github.com/rstudio/learnr/blob/master/R/exercise.R#L207-L209

**Comment by jjallaire** [comment]
Okay, @bborgesr can you take a shot at that?

**Comment by jcheng5** [comment]
@jjallaire She's out this week. I'll submit a PR momentarily.
