### ISSUE TITLE
Feature request: text input fields for student answers

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#156]
I would like to build exercises that use the equivalent of Shiny's numeric input and text input widgets to collect student responses. For example, I would like to write a prompt and then insert a text field for the student to write in, e.g.

> Which species of iris has the largest average petal length?
> TEXT FIELD

Ideally, I could supply answer() options as with question(). The text box would match student submissions to answers, ignoring case, whitespace, and misspellings(?). learnr would return the message associated with the matched answer (as well as the correct = ? status). If the submission is not matched to an answer(), learnr would return the general message provided to the text box.

One immediate application for this would be to transition students from the learnr tutorial environment to the full-blown IDE. Students could do their work in the IDE and then submit their "answer" in the text box for grading. A second application would be case studies (which would also require work in the IDE).

It is possible to tell the student to write text in the existing exercise box, but explaining this would be a distraction to the lesson (and may break the checker function).

**Comment by katossky** [comment]
I would use this feature for instance to ask student to fill-in some missing words in a text, in order to force them to actively read some explanations.

**Comment by schloerke** [comment]
Closed in https://github.com/rstudio/learnr/pull/194
