### ISSUE TITLE
Disable/tone down code completion?

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#161]
The new code completion is too aggressive for my tastes.  Parenthesis matching, in particular, is annoying when editing code stubs.  (I always disable this in RStudio as well -- worst idea ever for my typing skills.)

Are there ways to tone down the code completion a bit?

**Comment by jjallaire** [comment]
you can disable it as documented here: https://rstudio.github.io/learnr/exercises.html#code_assistance

**Comment by rpruim** [comment]
Excellent.  Looks like it is all or nothing for now, correct?

FWIW, here's what I like
 * no paren inserting (I can type those myself)
 * code completion only when I hit tab (I'll ask for help when I want it)

(Oh, and vi keybindings ;-)

**Comment by schloerke** [comment]
Closing for now as disabling is possible.

Moving tab completion discussion to https://github.com/rstudio/learnr/issues/188
