### ISSUE TITLE
Code render lag when used with slidy

### ISSUE THREAD

**Issue by coatless** [rstudio/learnr#164]
Sometimes when I try to execute code with `learnr` in a `slidy` deck, the code "lags" out and no output is transmitted. What ends up being displayed in the "R Markdown" tab is:

```bash
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'exercise.knit.utf8'
```

Now, this error comes up regardless of whether I have `title` or `author` keys in the YAML header.
What's particularly odd is when I switch the `output` type away from `slidy_presentation` to `ioslides_presentation` the render lag disappears, but the error message is present. 

Examples:

**slidy**

![slidy-learnr-issue](https://user-images.githubusercontent.com/833642/41187262-2e179b54-6b6b-11e8-8e85-7c9c48e77b18.gif)

**ioslides**

![ioslides-learnr-issue](https://user-images.githubusercontent.com/833642/41187387-99b57028-6b6d-11e8-901f-3ed473ae5279.gif)

**test3.Rmd**

````
---
title: "Demo ggplot2"
author: "JJB"
output: slidy_presentation
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(ggplot2)
```

## Some content

EDA is great!

## Example ggplot2

Swap the x and y variables. How does it affect the plot? 

```{r ggplot-options, exercise=TRUE, fig.height=5.5}
ggplot(mtcars) +
  aes(x = cyl, y = mpg) +
  geom_point()
```
````

-------

<details>
  <summary>Render of the RMarkdown Document</summary>

```bash
Loading required namespace: shiny


processing file: test.Rmd
  |................                                                 |  25%
  ordinary text without R code

  |................................                                 |  50%
label: setup (with options) 
List of 1
 $ include: logi FALSE

  |.................................................                |  75%
  ordinary text without R code

  |.................................................................| 100%
label: ggplot-options (with options) 
List of 2
 $ exercise  : logi TRUE
 $ fig.height: num 5.5


output file: test.knit.md

/usr/local/bin/pandoc +RTS -K512m -RTS test.utf8.md --to slidy --from markdown+autolink_bare_uris+ascii_identifiers+tex_math_single_backslash+smart --output test.html --email-obfuscation none --template /Library/Frameworks/R.framework/Versions/3.5/Resources/library/rmarkdown/rmd/slidy/default.html --id-prefix section- --mathjax --variable 'mathjax-url:https://mathjax.rstudio.com/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML' --highlight-style pygments 

Output created: test.html

Listening on http://127.0.0.1:6840
[WARNING] This document format requires a nonempty <title> element.
  Please specify either 'title' or 'pagetitle' in the metadata.
  Falling back to 'exercise.knit.utf8'
```

</details>

<details>
<summary>`sessionInfo()`</summary>

```r
R version 3.5.0 (2018-04-23)
Platform: x86_64-apple-darwin15.6.0 (64-bit)
Running under: macOS High Sierra 10.13.4

Matrix products: default
BLAS: /System/Library/Frameworks/Accelerate.framework/Versions/A/Frameworks/vecLib.framework/Versions/A/libBLAS.dylib
LAPACK: /Library/Frameworks/R.framework/Versions/3.5/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

loaded via a namespace (and not attached):
 [1] compiler_3.5.0  backports_1.1.2 bookdown_0.7    magrittr_1.5    rprojroot_1.3-2 htmltools_0.3.6
 [7] tools_3.5.0     yaml_2.1.18     Rcpp_0.12.17    stringi_1.1.7   rmarkdown_1.9   blogdown_0.6   
[13] knitr_1.20      xfun_0.1        stringr_1.3.0   digest_0.6.15   evaluate_0.10.1
```

</details>

**Comment by jjallaire** [comment]
The warning should have been fixed w/ a commit from a couple of months ago: https://github.com/rstudio/learnr/issues/154

This might not yet be on CRAN though.

**Comment by coatless** [comment]
@jjallaire #154 fixes the meta data warning, but the code lag persists under the `slidy_presentation` output.


![slidy-render-lagged](https://user-images.githubusercontent.com/833642/41193923-46e495d8-6bd9-11e8-9ece-c39f47048a28.gif)

**Comment by jjallaire** [comment]
No idea about the lag (there should be no difference at all for tutorials
within presentations)

**Comment by coatless** [comment]
It seems like the `slidy_presentation` isn't been refreshed within the browser window. Manually triggering a refresh seems to update the results.

c.f. 

![screen shot 2018-06-09 at 8 26 32 pm](https://user-images.githubusercontent.com/833642/41197424-a8e0c398-6c23-11e8-8508-6aa7580f1275.png)

![screen shot 2018-06-09 at 8 28 35 pm](https://user-images.githubusercontent.com/833642/41197428-d9831b36-6c23-11e8-9a20-62122341f6ad.png)

Is there a good spot to learn more about `runtime: shiny_prerendered` and how to add it to custom templates?

**Comment by jjallaire** [comment]
The docs on shiny_prerendered are here: https://rmarkdown.rstudio.com/authoring_shiny_prerendered.html

The output not showing up is very puzzling (it's not a lag it's just never there on my system). @bborgesr and @jcheng5 the example that @coatless repros the issue for me in slidy_presentation (but it doesn't happen in html_document or islides_presentation). I suspect something about the way slidy_presentation handles DOM visibility and how that interacts with Shiny outputs. Could one of you take a look?

**Comment by coatless** [comment]
@bborgesr & @jcheng5 did either of you have a moment to dig into why the `slidy_presentation` isn't able to play nicely with shiny outputs?

**Comment by schloerke** [comment]
Closed in https://github.com/rstudio/rmarkdown/pull/1717
