### ISSUE TITLE
Invalidation of locally stored worked by changing ID and version does not work

### ISSUE THREAD

**Issue by petzi53** [rstudio/learnr#165]
I followed the explanation from [Preserving Work](https://rstudio.github.io/learnr/index.html#preserving_work) and added ID and version to the yaml header. But whenever I changed ID and/or the version number, I always got my last exercise trial.

More detail on my failed trials on [StackOverflow](https://stackoverflow.com/questions/50783797/learnr-how-to-invalidate-stored-worked-locally-by-changing-id-and-version).

**Comment by jjallaire** [comment]
Locally stored work doesn't use the ID unfortunately. Local tutorial storage can be found at:

```r
file.path(rappdirs::user_data_dir(), "R", "learnr", "tutorial", "storage")
```

**Comment by petzi53** [comment]
Thank you for providing the path. Relating to the invalidating issue: In the meanwhile, I am already accustomed to clicking at the `Start over` button.
