### ISSUE TITLE
Replace style for monospaced code font?

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#171]
The default pink styling for monospaced code fonts (i.e. text surrounded by `) seems jarring. I suspect that it makes tutorials difficult to read, especially when the reader has to frequently transition between code font and normal font as in the text below. 

<img width="799" alt="screen shot 2018-07-19 at 10 42 24 am" src="https://user-images.githubusercontent.com/85014/42953815-d349b626-8b40-11e8-8399-7f97da86dc3b.png">

This gets worse when the text also uses bold or italic fonts.

Is it possible to replace the default pink font with a semibold black monospaced font on a white background?

**Comment by jjallaire** [comment]
I just changed the color to `darkslategray` here: https://github.com/rstudio/learnr/commit/53836c70c0f60dda95d48217878f1cc401083b40

This is what it looks like:
<img width="832" alt="screen shot 2018-07-23 at 9 17 10 am" src="https://user-images.githubusercontent.com/104391/43078733-4ed28a78-8e59-11e8-872e-960f0d15fb72.png">

cc @robbyshaver Let us know if you think this coloring works okay.

**Comment by garrettgman** [comment]
I like the dark slate grey! Is it possible to make the text background grey as well? At the moment, the background appears to be pink:

<img width="715" alt="screen shot 2018-10-02 at 3 59 37 pm" src="https://user-images.githubusercontent.com/85014/46376684-38616d00-c65c-11e8-83dd-04901170dffd.png">
