### ISSUE TITLE
Hints only work if I have something in the exercise box

### ISSUE THREAD

**Issue by KatherineCox** [rstudio/learnr#172]
* If I have some code in the exercise box, hints work as expected.  
* If there is no code in the exercise box, then the code (that's supposed to be a hint) is just run below the box and no hint button is displayed.
* Adding a single newline in the exercise box is sufficient to make the hints work, but if I don't have anything, it breaks.

````
---
title: "Introduction to R"
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
tutorial_options(exercise.completion=TRUE)
knitr::opts_chunk$set(echo = FALSE)
```

## Dataframes

Use the code block below to explore the built-in `mtcars` dataframe, which contains several pieces of data about car design and performance (originally from the 1974 Motor Trend US magazine).

Something in the exercise box means the hints work
```{r dataframe-exercise, exercise=TRUE}
mtcars
```

```{r dataframe-exercise-hint-1}
mtcars$mpg
```


Nothing in the exercise code leads to broken hints:
```{r dataframe2-exercise, exercise=TRUE}
```

```{r dataframe2-exercise-hint-1}
mtcars$mpg
```

Even a single newline is sufficient to make the hints work:
```{r dataframe3-exercise, exercise=TRUE}

```

```{r dataframe3-exercise-hint-1}
mtcars$mpg
```

````
<img width="737" alt="screen shot 2018-07-26 at 4 01 05 pm" src="https://user-images.githubusercontent.com/13210811/43285868-522ae296-90ee-11e8-9477-48c1f34718c4.png">

**Comment by schloerke** [comment]
@KatherineCox Yes, I believe this is related to #410. #411 should fix #172.

cliff notes: `knitr` interprets chunks with 0 content to have a `NULL` body, which looks just like a missing chunk.

Ex:

```r
Browse[1]> get_knitr_chunk("does-not-exist")
NULL
Browse[1]> get_knitr_chunk("dataframe2-exercise")
NULL
Browse[1]> get_knitr_chunk("dataframe3-exercise")
[1] ""
attr(,"chunk_opts")
attr(,"chunk_opts")$label
[1] "dataframe3-exercise"

attr(,"chunk_opts")$exercise
[1] TRUE
```

`get_knitr_chunk("dataframe2-exercise")` should be returning _some_ sort of result.
