### ISSUE TITLE
Security of code exercises

### ISSUE THREAD

**Issue by oskotsky** [rstudio/learnr#177]
It seems like students of a tutorial have freedom of running arbitrarily code in the code exercises chunks. Is there simple way to limit what students could actually run to a set of commands? It would be great for publicly open sites running learnr. Maybe we just didn’t find this in tutorial but built in already? Checkr and vignettes seems to be overly complicated for this task.

Thank you

**Comment by jjallaire** [comment]
Here are some notes on security considerations: https://rstudio.github.io/learnr/publishing.html#security_considerations

Here's an example of how you could create a custom execution environment for tutorials using AppArmor: https://rstudio.github.io/learnr/publishing.html#exercise_execution

Yes, this is pretty complicated. Our hope is that hosting services like https://rstudio.cloud will provide a way to host tutorials within a container that has good isolation.

**Comment by oskotsky** [comment]
Thank you! We will look through these.
