### ISSUE TITLE
Default RStudio keyboard shortcuts in learnr?

### ISSUE THREAD

**Issue by kendonB** [rstudio/learnr#187]
It would be awesome if the learnr tutorials behaved the same way as RStudio, including having the default keyboard shortcuts.

**Comment by JosiahParry** [comment]
I want to +1 this. Tried using `command + shift + m` for `%>%` and it didn't work. I think it would be nice to mostly replicate the development flow within `learnr`.

**Comment by gadenbuie** [comment]
I added support for inserting `%>%` and `<-` (or `=` in other languages) in #472. The shortcuts for both should be equivalent to their RStudio counterparts: `Command/Control + Shift + M` and `Alt + -`

**Comment by averyrobbins1** [comment]
The pipe and assignment shortcuts don't seem to work for me when I run a learner document locally. Has anyone else had problems?
