### ISSUE TITLE
Feature request: Extend multiple choice question grading paradigm to code exercises

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#191]
After experimenting with writing a [code grading package](https://github.com/rstudio-education/grader), I think the most flexible way to provide easy-to-use grading tools is to recreate the multiple choice grading scheme for code exercises (and also for fill-in-the-blank exercises).

## Goal

The goal is to let tutorial authors list likely code results (including the correct result), and to assign a custom message to be displayed for each result. When a student clicks Submit Code, learnr will evaluate the code and match the student result against the enumerated results. 

* If a match is found, learnr will display the message associated with the match. 
* If a match is not found, learnr will display a default message. 
* If the student code returns an error, the error is displayed in the learnr tutorial (alternatively/eventually authors will be able to match errors with custom messages to display).

## Requirements (suggested)

1. A function that authors can call in the `-check` chunk that accompanies an exercise. This function is an analogue to the `question()` function for multiple choice questions. I'll call it `match_result()` below, but we can choose a better name. 

    Where sensible, `match_result()` should repeat the arguments of `question()` (e.g. `allow_retry` and `incorrect` (which provides the default message to display if none of the enumerated results are matched)).

2. A function that can be passed to `match_result()`. This function is an analogue to `answer()` Authors can use it to list possible results for a code exercise. I'll call this function `result()`. 

    `result()` should differ from `answer()` in that the author can pass an R object, instead of a character string, to the first argument of `result()` (we should check for NSE issues here). 

    `result()` should resemble `answer()` in that the author can use the arguments of `result()` to identify the correct result and to provide a message to display if the student result matches the result. 

    Preferably, `answer()` and `result()` can be combined into the same function, but I do not know if that is possible.

3. A "`collect`" argument for `match_result()`. This argument should default to `NULL`, but should accept an R expression (as a character string?) to be provided by the tutorial author. When `collect` does not equal `NULL`, learnr should run the provided code on the exercise environment as it is after the student code has been evaluated. `match_result()` will then match the result of the `collect` expression against the enumerated results. This argument is designed to help authors fetch the results of exercises that involve creating objects, defining functions, etc. 

    When `collect = NULL`, `match_result()` will match the result returned by the student code against the enumerated results.

    If `collect = NULL` and the student code does not return a result, `match_result()` should display a message like "I did not notice a result. Does your code return one?"

4. If the student response is empty, `match_result()` should return a message like "I did not see your code. Did you write any?"

5. When run, `match_result()` should enter an event with the learnr event recorder. The event should capture the student ID, the exercise label, possibly the student code, and definitely the outcome: correct or incorrect.

## Example UI

Here's an example of how this would look in tutorial .Rmd

### Exercise 1

* Create an object named `x`. Assign into it the result of `1 + 1`. Then click Submit Answer

````
```{r ex1, exercise = TRUE}

```
````

````
```{r ex1-solution}
x <- 1 + 1
```
````

````
```{r ex1-check}
y <- list(a = list(1, 2), b = TRUE)

match_result(collect = "x",
             result(2, correct = TRUE, "Good Job! 1 + 1 = 2."),
             result(3, "1 + 1 does not equal three. Check your work. I think you made a typo."),
             result(0, "Did you write one _minus_ one?"),
             result(y, "Wow. If you can create hierarchical lists, you should probably skip to the next tutorial."),
             incorrect = "That is not the correct answer.",
             allow_retry = TRUE)
```
````
## Commentary

The advantage of this approach is that the tools will be simple to use and robust. Authors can re-apply their knowledge of multiple choice questions to grading code exercises.

The disadvantage is that the tools cannot tell the student _why_ they got a wrong answer unless the author identifies the student's failure mode (and the associated result) ahead of time. However, authors should be able to spot and check for common mistakes (especially after they review the initial round of tutorial logs).

I've made good progress writing a [code checker](https://github.com/rstudio-education/grader) that can analyze user code itself and return a sensible message in most cases. However, I believe it will take an order of magnitude more development time to make checking code (instead of results) robust. If we leave in the checking hooks, users can choose to develop and use such a checker at their discretion.

**Comment by garrettgman** [comment]
Reviewing this, I think it will be important to let authors match error messages as well as results right off the bat (in our first release). Why? Because many failure modes will result in a known error message.

**Comment by schloerke** [comment]
This issue is being addressed here: https://github.com/rstudio-education/grader/issues/11
