### ISSUE TITLE
cannot open the connection on shinyapps.io while using load("data.Rdata")

### ISSUE THREAD

**Issue by pokyah** [rstudio/learnr#195]
Hi all ! 

I've succeeded to build my tutorial and deploy it to [shinyapps.io](https://pokyah.shinyapps.io/spagrometeor/).

Here is its [source code](https://github.com/pokyah/foss4GBXL2018_tuto).

In the `walOSM` exercice code chunk (line 437 of tuto.Rmd file) I want to load  belgium.Rdata.
The codes perfectly works locally nut not on shinyapps.io

**My question : how to load an existing .RData object from within an interactive exercise when hosted on shinyapps.io ? Where should the .RData file be stored (inside /www ?) and how to allow the exercise users to effectively load theses objects ?**

Thanks in advance for your precious help

**Comment by schloerke** [comment]
@pokyah Hmmmm. Your code looks ok, even if your `RData` line was uncommented.

If you ever run into a situation that seems like it should work, check on https://community.rstudio.com/c/general and tag it with `shinyappsio`.  The community response much quicker than I will.

**Comment by schloerke** [comment]
Closing as issue is unrelated to learnr
