### ISSUE TITLE
use result of last statement in exercise.checker function

### ISSUE THREAD

**Issue by jessekps** [rstudio/learnr#198]
Hi,

A natural thing to do in R is to type a statement in the console and inspect the result. If a reader does this in an exercise I would like to use the result of the last statement in an exercise.checker function. Since it's nameless, it's not in envir_result. Evaluate_result contains a representation of the last statement but not the value of the R object. I currently use `try(eval(user_code))` but that slows things down since the same code is now evaluated twice.

Is there a better option to get at this value? If not, could it be added?

Thanks!

**Comment by schloerke** [comment]
Notes: When eval'ing results, store eval to `last_result` or something

**Comment by schloerke** [comment]
@jessekps Thank you for the Issue!
