### ISSUE TITLE
Conditions in learnr

### ISSUE THREAD

**Issue by ghost** [rstudio/learnr#199]
I'm using learnr to make some exercises. Specifically, all these exercises are in the form of questions, as shown below:
```

```{r question1, echo=FALSE}
question(ques_1,
          answer(ques_1_ans_1),
          answer(ques_1_ans_2),
          answer(ques_1_ans_3),
          answer(ques_1_ans_4, correct = TRUE))

```

I'd like to check what proportion of questions the students answered correctly, and if the student's proportion of correct answers does not exceed 50%, I'd like to make them repeat the set of questions from the beginning. Any ideas?

**Comment by schloerke** [comment]
Currently this is out of scope for `learnr` as each question is independently implemented to no knowledge of other questions and their results.  

Closing the issue for now as there are no plans to address it
