### ISSUE TITLE
run_tutorial() bug?

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#208]
If I try to run a tutorial in a package with `run_tutorial()`, I'm getting the following error message:

```
ERROR: Couldn't normalize path in `addResourcePath`, with arguments: `prefix` = 'bootstrap-3.3.5'; `directoryPath` = ''
```

I see a note about this at <https://community.rstudio.com/t/learnr-run-tutorial-not-working-on-rstudio-cloud/20674> but it doesn't appear to be limited to rstudio.cloud; I'm seeing this in the console of the desktop version of RStudio as well.  Not sure if this is a learnr issue or an RStudio issue.

Also, it would be nice if

* the `run_tutorial()` help page included an example use (not run)
* missing `name` would yield a list of available tutorials in a package (much like the `data()` function does for data sets).  Is there some other way to discover available tutorials?

**Comment by schloerke** [comment]
I really like the missing name feature.  

I'll add an example in run tutorial.

**Comment by schloerke** [comment]
See https://github.com/ScPoEcon/ScPoEconometrics/blob/a9b19c450401d53ef3a22268d590e445e3a0de27/R/runexample.R#L7

**Comment by bjcairns** [comment]
I found this issue after searching for the same error message as @rpruim got (R 3.5.3, RStudio Desktop, learnr installed from CRAN this morning). The problem exists for both the `"hello"` and `"slidy"` tutorials. Picking through `run_tutorial()` I found that if I re-rendered hello.html then it worked, e.g. (adapting code from the `run_tutorial` function):

```r
tutorial_path <- system.file("tutorials", "hello", package = "learnr")
shiny_args <- list(launch.browser = interactive())
withr::with_dir(
  tutorial_path,
  rmarkdown::run(file = NULL, dir = tutorial_path, shiny_args = shiny_args)
)
```

Then interrupt R to stop the Shiny app. Reinstalling the binary package from CRAN recreates the problem; running the above again fixes it. 

I had no issue with the source package or installing from GitHub, but in these cases hello.html was rendered when I used `run_tutoria("hello", package = "learnr")` as (I guess) it is only pre-rendered in the binary package.

It looks like the bug might be confined to these pre-rendered .htmls in the current CRAN binary of learnr, and in any case re-rendering as above may be a temporary fix for anyone with the same trouble.

For reference here's my session info after running the temporary fix (i.e. with relevant packages loaded/attached):
<details>

```
> sessionInfo()
R version 3.5.3 (2019-03-11)
Platform: x86_64-w64-mingw32/x64 (64-bit)
Running under: Windows >= 8 x64 (build 9200)

Matrix products: default

locale:
[1] LC_COLLATE=English_United Kingdom.1252  LC_CTYPE=English_United Kingdom.1252   
[3] LC_MONETARY=English_United Kingdom.1252 LC_NUMERIC=C                           
[5] LC_TIME=English_United Kingdom.1252    

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] learnr_0.9.2.1 shiny_1.3.1   

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.1      knitr_1.22      magrittr_1.5    rappdirs_0.3.1  xtable_1.8-3   
 [6] R6_2.4.0        rlang_0.3.4     stringr_1.4.0   tools_3.5.3     xfun_0.6       
[11] withr_2.1.2     htmltools_0.3.6 yaml_2.2.0      rprojroot_1.3-2 digest_0.6.18  
[16] later_0.8.0     htmlwidgets_1.3 promises_1.0.1  evaluate_0.13   mime_0.6       
[21] rmarkdown_1.12  stringi_1.4.3   compiler_3.5.3  backports_1.1.4 jsonlite_1.6   
[26] httpuv_1.5.1    markdown_0.9   
```

</details>

**Comment by schloerke** [comment]
@bjcairns You are correct.  

The run_tutorial bug about dependencies not being found should be fixed in https://github.com/rstudio/learnr/issues/169. (This is why it currently works with github version.)

Cliff notes of the issue: If I prerender my tutorial using myPkg v1.0 and it has some external dependencies and then send the tutorial to you.  You have myPkg v1.1 which has different external dependencies.  When you attempt to render, the dependencies are not found.  This causes a render error.  Fix was to store the package versions in the prerender document.  If any pkg version doesn't agree, rerender the document.

**Comment by schloerke** [comment]
Closing this issue in favor of #169 .  Other raised questions have been made into their own issues.
