### ISSUE TITLE
Ability to discover tutorials from a package

### ISSUE THREAD

**Issue by schloerke** [rstudio/learnr#224]
Originally from @rpruim in https://github.com/rstudio/learnr/issues/208

> missing name would yield a list of available tutorials in a package (much like the data() function does for data sets). Is there some other way to discover available tutorials?

Make a `available_tutorials()` function.  Run this function as the error message when a tutorial isn't found in `run_tutorial()`

**Comment by rpruim** [comment]
Thanks.  Looking forward to these feature!

**Comment by rpruim** [comment]
Thanks again.

**Comment by schloerke** [comment]
@rpruim  Great bug! Thank you!

I've added an `adist` functionality.  So if you're close, you'll get some suggested options.

``` r
learnr::run_tutorial("helloo", "learnr")
#> Error: Tutorial "helloo" was not found in the "learnr" package.
#> Did you mean "hello"?
#> Available tutorials:
#> * learnr
#>   - hello         : "Hello, Tutorial!"
#>   - question_type : "Question Types in Learnr"
#>   - slidy         : "Slidly demo"
```

<sup>Created on 2019-06-06 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by rpruim** [comment]
Love it.  This should help the tutorial get more use.
