### ISSUE TITLE
Deploying Tutorial as package - including tutorials subdirectory

### ISSUE THREAD

**Issue by mpfp** [rstudio/learnr#232]
Hi All,

I'm making my first attempt to deploy a learnr tutorial in a package.  I've tried several things, but I can't figure out how to include the 'tutorials' directory in the package file.  When I run run_tutorial, I get a message that it can't find the tutorial.  It's not included in the tar.gz.  I'm sure I'm missing something simple, but can't figure out how to direct R to include the tutorials directory.

`> learnr::run_tutorial("datawrangle", package = "rtutorials")`

`Error in learnr::run_tutorial("datawrangle", package = "rtutorials") : 
  Tutorial datawrangle was not found in the rtutorials package.
`

Is there a better place (discussion form for learnr) to post this question?

Matt

**Comment by jjallaire** [comment]
You need to put it in the "inst" subdirectory of package source folders.

**Comment by mpfp** [comment]
Thanks for your reply, JJ.  Do you mean the html file or the entire 'tutorials' directory.  If I place the tutorials directory under inst, then run_tutorial launches a webpage, but displays "Page Not Found" (yes the html file is generated).  If I just place the HTML file in inst, then run_tutorial gives me the same error.

Is there a recommended way for creating a package project for a learnr tutorial?  I created a blank package and added the learnr interactive tutorial to it.

**Comment by mpfp** [comment]
Here's the answer to my question.  The entire tutorial folder needs to be inside the inst directory.  A careful re-read of the instructions (https://rstudio.github.io/learnr/publishing.html) revealed this.
