### ISSUE TITLE
there is no package called ‘checkthat’ 

### ISSUE THREAD

**Issue by lixingguang** [rstudio/learnr#233]
> library(learnr)
> library(tidyverse)
> nycflights <- nycflights13::flights
> tutorial_options(exercise.eval = TRUE)
> tutorial_options(exercise.checker = checkthat::check_exercise)
 Error in loadNamespace(name) : 

- [ ] there is no package called ‘checkthat’

**Comment by schloerke** [comment]
Correct.  It is confusing documentation.  I am currently working on [`grader`](https://github.com/rstudio-education/grader) which would implement the functionality.  (I do not know of an existing checking package.)

**Comment by chendaniely** [comment]
I'm working on this.

**Comment by schloerke** [comment]
Closed in #273
