### ISSUE TITLE
Error: Can't calll `runApp()` from within `runApp()`

### ISSUE THREAD

**Issue by wlandau** [rstudio/learnr#237]
I am having trouble using `shinytest` on prerendered R Markdown documents ([reprex here](https://github.com/wlandau/shinytest-learnr-reprex)). The [example `learnr` tutorial](https://github.com/wlandau/shinytest-learnr-reprex/blob/master/example/example.Rmd) works fine with `rmarkdown::run()`, but `recordTest()` seems to think I am calling `runApp()` from within `runApp()`. I get the same error when I try to deploy similar apps to my company's instance of Shiny Server.

**Comment by wlandau** [comment]
Sorry, I just realized this is a better issue for `rmarkdown`.

**Comment by schloerke** [comment]
@wlandau Would be great for [`shinyTest`](https://github.com/rstudio/shinyTest/issues).  I believe the errors are there.

Thank you for the reprex and unexpected errors/output!!

**Comment by wlandau** [comment]
Glad you think this helps, Barret.

A colleagued noticed that in the case of Shiny Server, I needed to deploy the Rmd source instead of an `app.R` file. That worked for me, and it makes sense. For `learnr`, it seems like we could direct folks to https://rstudio.github.io/shinytest/articles/package.html#applications-in-inst instead of https://rstudio.github.io/shinytest/articles/package.html#application-objects-created-by-functions. Until now, I have been using the latter.

**Comment by schloerke** [comment]
`inst` directory is correct.  All tutorials are in a pkg's `inst` folder even if they are launched by another function.
