### ISSUE TITLE
Looping a while or For loop to get question/answers through a csv

### ISSUE THREAD

**Issue by amolgogate** [rstudio/learnr#277]
Hi,

Sorry if this would have been answered. Is there any way to loop around a set of questions and answers saved in a csv and display them? I tried retrieving data in a csv by creating a dataframe but I cant seem to display the questions looped through using a for loop. This code doesnt seem to work for some reason.
*******************
for (i in 1:5){
 
  a1 <- answer("Whether or not the vehicle has driver side airbags")
  a2 <- answer("Whether a car is automatic or manual transmission")
  a3 <- answer("The number of cylinders in the car's engine")
  a4 <- answer("Something else", correct = TRUE, message = "`drv` describes the type of drivetrain in a car: front  wheel drive, rear wheel drive, or four wheel drive.")

question('q1' ,a1,a2,a3,a4,
                 allow_retry = TRUE)
}
*************************************
Not sure what I am missing. Any simple examples will be helpful.

Thanks in advance.

-Amol

**Comment by schloerke** [comment]
If they are to be displayed back to back, I believe a `quiz` would solve the problem.

```r
# collect all of the questions (similar to above)
questions <- lapply(1:5, function(i) {

  a1 <- answer("Whether or not the vehicle has driver side airbags")
  a2 <- answer("Whether a car is automatic or manual transmission")
  a3 <- answer("The number of cylinders in the car's engine")
  a4 <- answer("Something else", correct = TRUE, message = "drv describes the type of drivetrain in a car: front wheel drive, rear wheel drive, or four wheel drive.")

  question('q1' ,a1,a2,a3,a4, allow_retry = TRUE)
})

# call `quiz` with an extra `caption` argument and all of the questions
do.call(quiz, c(caption = "QUIZ TITLE", questions))
```

**Comment by amolgogate** [comment]
Thank you so much for your reply. I was able to execute the code snippet and should be able to use this technique.
