### ISSUE TITLE
Images in questions.

### ISSUE THREAD

**Issue by amolgogate** [rstudio/learnr#278]
Hello,

Is there any  way to set an image for a question? i.e can I set any property which will load an image for a question?

If not can this be a feature request?

Thanks,
AG

**Comment by schloerke** [comment]
Yes!  This should work with any `question_*` method.

In the next release...  Using an example question of


```{r question}
question_radio(
  "**Text** before ![title](http://dreamicus.com/data/image/image-06.jpg) text after",
  answer("Coastline: ![coastline](https://html5box.com/html5gallery/images/Waves_1024.jpg)", correct = TRUE)
)
```

Produces:

![Screen Shot 2019-09-18 at 1 40 13 PM](https://user-images.githubusercontent.com/93231/65171909-f7ec3200-da19-11e9-8795-d26eb9bdc5af.png)

**Comment by amolgogate** [comment]
Great!Thank you for including it in the next Release. 

Look forwarding working with that version. 

Any tentative release dates at this stage?

Thanks,
AG

**Comment by schloerke** [comment]
I've been ready for a month.  Waiting on `renv` to make it to CRAN.  It's been a long process for `renv`.
