### ISSUE TITLE
Feature Request: serverless questions?

### ISSUE THREAD

**Issue by njtierney** [rstudio/learnr#282]
Hi there! 

Thanks for making `learnr`, such a neat package with a great interface!

I'd like to be able to include simple multi-choice, true false, or even string match questions in various html places - such as bookdown/presentations/html.

At the moment this becomes challenging with `learnr` as you need to have a server to serve up the questions.

What I want is a way to ask people an MCQ question, and then for a radio button interface to be presented, which knows if it is right or wrong - I'm not interested in storing this information anywhere, just present the question - basically I want to use the same interface that `learnr` provides: https://community.rstudio.com/t/create-questions-and-quiz-in-learnr-rmarkdown-document/17951

```{r quiz1, echo=FALSE}
quiz(caption = "Quiz 1",
  question("What number is the letter A in the *English* alphabet?",
    answer("8"),
    answer("14"),
    answer("1", correct = TRUE),
    answer("23")
  ),
  question("Where are you right now? (select ALL that apply)",
    answer("Planet Earth", correct = TRUE),
    answer("Pluto"),
    answer("At a computing device", correct = TRUE),
    answer("In the Milky Way", correct = TRUE),
    incorrect = "Incorrect. You're on Earth, in the Milky Way, at a computer."
  )
)
```

I understand that this might be out of scope for `learnr`, so I am very happy to spin this out into it's own light-weight package, but I thought that I should check here before I do that, in case it is something you have thought about or feel is in scope?

**Comment by schloerke** [comment]
Hi Nicholas!

Two things are at play:
1. Next version of `learnr` (releasing once `renv` is accepted) will have `shiny` based questions.  All questions will be backed by `shiny`.  
2. With the next version on `learnr` being backed by `shiny`, all validation is done within `shiny`.

Adopting this for `learnr` natively is out of scope for my work.   However, I think there is something we can work with. The new `quiz` questions are built around a question API.  See (on GitHub master branch) `learnr::run_tutorial("quiz_question", "learnr")` .  

I'm thinking you could make a `question_static_radio` method that wraps around `question_radio`, but adds a class of `static_question` to the `question` object returned from `question_radio`.  Then, a `knit_print.static_question` could be added which will call `question_ui_initialize` and return html tags:
```r
knit_print.static_question <- function(x, ...) {
  question_ui_initialize(x) %>%
    htmltools::as.tags()
}
```

This would at least display the ui.  It would also require the that ui being rendered is complete at compile time (not needing `shiny` to be initially displayed).

(Names above can be changed!)

-------------------

I believe the blueprint above should make it possible.

I would suggest making a new package.  We have intentionally done this with [sortable](http://github.com/rstudio/sortable) and [parsons](http://github.com/rstudio/parsons) as `learnr` quiz question extension packages. 

I would be happy to help guide / code review.  It would be good to see the `learnr` quiz question api succeed. 

Thank you for the interest!


---------- 

Side note: I strongly believe static exercises should not be attempted.  The point is to evaluate code and get an answer.  Adding a "simple ace text editor" is _easy_, but I don't think it would serve a purpose.

**Comment by njtierney** [comment]
Thanks, @schloerke ! :)

Yes, I agree that static code exercises are not in the scope for `quizlite` (or whatever the package is called!) - I think I would limit it to just TRUE/FALSE or radio button selection.

Thank you for the encouragement re the package and the code templates/guidance :)

I probably won't have bandwidth to work on this until November/December, but I will ping you when I do!


Thanks again!
