### ISSUE TITLE
Remove radio button for option that is incorrect, when trying again

### ISSUE THREAD

**Issue by chapmjs** [rstudio/learnr#284]
Is there a way to remove the radio button for an incorrect option when try again is selected?

(for retry_allow questions)

**Comment by schloerke** [comment]
Currently no. 

I don't believe this is possible in the near future either with the generalized quiz questions.  When the API was built, submission history was not considered.  

---------

Closing for now as it's out of scope.  It might be possible if someone built a custom wrapper around `question_radio` that maintained submission history.
