### ISSUE TITLE
kable tables

### ISSUE THREAD

**Issue by cristianchagalj** [rstudio/learnr#286]
I think there is a problem with the kable tables in the new learnr#271 package.

CRAN's package result:

![cran_package](https://user-images.githubusercontent.com/7211418/67175881-b989c000-f395-11e9-9a1f-2f1223dcbb0c.JPG)

learnr#271 package result:

![github_package](https://user-images.githubusercontent.com/7211418/67175887-c4dceb80-f395-11e9-8fa8-6a0c3f31bc5a.JPG)

Thanks!

**Comment by schloerke** [comment]
@cristianchagalj Thank you for testing!!! 

Looking into this now
