### ISSUE TITLE
Show progress bars within sections

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#289]
From @gvwilson at https://github.com/rstudio-education/primers/issues/3:

"When working through the questions under any particular heading, I don't have any feeling for how much is left in the section. Some sort of progress bar showing how many sections or questions have been done/are left would be comforting."

**Comment by schloerke** [comment]
I believe there is very small vertical progress bars next to the section in the ToC.

**Comment by garrettgman** [comment]
You beat me to it @schloerke. I should've caught this before I moved it over. Here they are: 
<img width="1274" alt="Screen Shot 2019-10-28 at 1 34 06 PM" src="https://user-images.githubusercontent.com/85014/67702402-141faf00-f988-11e9-9e91-a08681f5efda.png">

**Comment by schloerke** [comment]
Np! Glad they're there. :-)
