### ISSUE TITLE
Incompatibilities with shinyapps.io and/or rsconnect

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#30]
The tutorial below can be deployed successfully to shinyapps.io from the RStudio IDE. But two small changes break the process (scroll down):

````
---
title: "Data Visualization Basics"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
library(ggplot2)
checker <- function(label, user_code, check_code, envir_result, evaluate_result, ...) {
  list(message = check_code, correct = TRUE, location = "append")
}
tutor_options(exercise.timelimit = 60, exercise.checker = checker)
```

## Aesthetic mappings

```{r aesthetics, exercise = TRUE, exercise.eval = FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r aesthetics-check}
"Great Job! You can now tell which class of car each point represents by examining the color of the point."
```
````

![screen shot 2017-03-03 at 4 39 42 pm](https://cloud.githubusercontent.com/assets/85014/23569958/1a6edfec-0030-11e7-871e-7c329913da91.png)

1. The tutorial goes grey as soon as it is opened on shinyapps.io if it does not include an R Markdown header, e.g.

````
---
title: "Data Visualization Basics"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
library(ggplot2)
checker <- function(label, user_code, check_code, envir_result, evaluate_result, ...) {
  list(message = check_code, correct = TRUE, location = "append")
}
tutor_options(exercise.timelimit = 60, exercise.checker = checker)
```

Aesthetic mappings (no heading)

```{r aesthetics, exercise = TRUE, exercise.eval = FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy))
```

```{r aesthetics-check}
"Great Job! You can now tell which class of car each point represents by examining the color of the point."
```
````

![screen shot 2017-03-03 at 4 39 53 pm](https://cloud.githubusercontent.com/assets/85014/23569981/2e20a5ca-0030-11e7-97a5-9731ec495840.png)

2. The tutor fails to deploy if an exercise includes example code with "fill in the blank" sections, like this (which we should expect):

````
---
title: "Data Visualization Basics"
output: tutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(tutor)
library(ggplot2)
checker <- function(label, user_code, check_code, envir_result, evaluate_result, ...) {
  list(message = check_code, correct = TRUE, location = "append")
}
tutor_options(exercise.timelimit = 60, exercise.checker = checker)
```

## Aesthetic mappings

```{r aesthetics, exercise = TRUE, exercise.eval = FALSE}
ggplot(data = mpg) + 
  geom_point(mapping = aes(x = displ, y = hwy, _________))
```

```{r aesthetics-check}
"Great Job! You can now tell which class of car each point represents by examining the color of the point."
```
````

![screen shot 2017-03-03 at 4 42 56 pm](https://cloud.githubusercontent.com/assets/85014/23570069/8fda4e4c-0030-11e7-9c90-dc124b1eef62.png)

Note: all of these examples work fine locally.

**Comment by jjallaire** [comment]
Thanks for the report! I'll look into both of these issues.

**Comment by jjallaire** [comment]
@kevinushey If you take the second Rmd file and run the following on it:

```r
packrat:::fileDependencies.Rmd("deploy.Rmd")
```
```
[1] "rmarkdown" "tutor"     "shiny"    
```

Whereas if you comment out the chunk with the invalid R code then you get this:

```
[1] "rmarkdown" "tutor"     "shiny"     "tutor"     "ggplot2"  
```

So the invalid R code is causing us to fail to detect dependencies (not that ggplot2 is not detected even though it's in a valid R chunk -- it looks like the unparseable code in the other chunk is causing all of our R parsing to fail.

@garrettgman I don't know if there is going to be an easy way around this as we rely on R code to be valid (parseable) in order to detect dependencies. Workarounds I can think of include:

1. Finding a way to create placeholders that are valid R code (e.g. XXXXXX rather than underscores). However this still leaves the problem of code chunks that are intended to be invalid (i.e. ones we ask the student to fix); or

2. Find a way to detect dependencies within Rmd files on a per-chunk basis; or

3. Including a separate `dependencies.R` file which includes a bunch of `library` calls to the packages you want included in the deployment.

**Comment by jjallaire** [comment]
@robbyshaver It looks like the first error is due to some JS in tutorial-format.js assuming there would be at least one section in the document:

<img width="953" alt="screen shot 2017-03-08 at 6 46 23 pm" src="https://cloud.githubusercontent.com/assets/104391/23729411/b2c070c8-042f-11e7-91e7-ea8c11ff8316.png">

**Comment by kevinushey** [comment]
Right, Packrat's dependency discovery uses the R parse tree to find dependencies, and so will barf i the file is not parsable. E.g. I see:

```
> packrat:::fileDependencies.Rmd("~/scratch/tutor.Rmd")
Warning in value[[3L]](cond) :
  Failed to parse /var/folders/tm/5dt8p5s50x58br1k6wpqnwx00000gn/T//RtmpLQ2WcA/file11f3727fbf696 ; dependencies in this file will not be discovered.
[1] "rmarkdown" "tutor"     "shiny" 
```

Note that Packrat will use `knitr::knit(tangle = TRUE)` to generate an R file from the `.Rmd` file, and then attempt to parse that file all at once for dependencies. Do we have a public function that will take an `.Rmd` and return the set of chunks as an R list?

**Comment by jjallaire** [comment]
knitr publicly exposes the regexes that it uses for parsing out both chunks and inline R expressions. You can access the `md` regexes here:

```r
knitr::all_patterns$md
```

So I think we could use those regexes to do our own extraction?

@yihui Is there a more straightforward way? Any other suggestions you have are welcome!

**Comment by kevinushey** [comment]
One thought: we could try knitting the document with a custom `evaluate()` hook, and just have that hook attempt to parse + populate the discovered dependencies.

**Comment by jjallaire** [comment]
I like that idea better than using the regexes. @yihui Let us know what you think.

**Comment by yihui** [comment]
There is an internal parser in knitr, but the idea of using a custom evaluate hook sounds better to me.

**Comment by robbyshaver** [comment]
Checked in a fix to tutor for the js error tutorial-format.js for documents without any topic sections.

**Comment by garrettgman** [comment]
@jjallaire would it work if we require authors to write solution chunks for each exercise and then parse the solutions chunks, and never the exercise chunks, for dependencies?

**Comment by jjallaire** [comment]
Once we can parse the chunks separately we'll be all set (chunks with
invalid R cod will just be skipped).

**Comment by garrettgman** [comment]
Hi guys, I'm wondering if there's been any progress on parsing (purposefully) invalid exercise code with packrat? This came up in a today's meeting with @tareefk (in which, I wrongfully attributed it to rsconnect, if you're reading). 

It would be very useful to give students code to complete and correct, which makes me think that most tutorial authors will try it.

**Comment by kevinushey** [comment]
We have a PR for this here: https://github.com/rstudio/packrat/pull/363

**Comment by pat-s** [comment]
I faced this issue when deploying to shinyapps.io and commented out all `__` code in my chunks.

Interestingly, all `#` comment signs are gone on shinyapps.io (see e.g. [here](https://pat-s.shinyapps.io/r_drivers_license/#section-euclidean-distance)) although the code in the .Rmd file looks like 

```
# __
```

This may also be important for the `checkr` package (@dtkaplan) as it even provides examples with `__` placeholders but does not address the deployment issue to shinyapps.io.

**Comment by dtkaplan** [comment]
I'm starting a revision/refactoring of `checkr`. I'll keep these deployment
issues in mind as I work.  Thanks!

**Comment by dasil-jarren** [comment]
Has there been any updates on this getting fixed?  I know that @PaulC91 ran into this issue again a bit ago, and I'm now running into this issue as well.

https://github.com/rstudio/learnr/issues/209

**Comment by gadenbuie** [comment]
I believe this has been fixed in https://github.com/rstudio/packrat/pull/551
