### ISSUE TITLE
tag learnr tutorials with extra metadata?

### ISSUE THREAD

**Issue by kevinushey** [rstudio/learnr#312]
As part of the Tutorial pane work in the RStudio IDE, I'd like to make a landing page for all discovered tutorials provided by any installed packages. It currently looks like this:

![Screen Shot 2019-12-16 at 3 10 18 PM](https://user-images.githubusercontent.com/1976582/70950874-b23e0600-2016-11ea-94a2-a3a695fe99ea.png)

The presentation is currently a bit bare. I wonder if there is some other relevant metadata we could include for a particular tutorial, e.g.

- A short, single-paragraph description? [description]
- The R package(s), if any, one might learn about in this tutorial? [packages]

The format I'm currently imagining would be something like:

> Data Basics [ex-data-basics]
> 
> Learn about the base data types in R. Explore R's data frames, and learn how to interact with data frames and their columns using dplyr.
> 
> Packages: dplyr, tibble

All the relevant data here could be included as part of the YAML header.

**Comment by coatless** [comment]
@kevinushey any way to render a thumbnail of the tutorial in the pane?

**Comment by kevinushey** [comment]
Not currently, but we could allow for something like `icon.png` if that would be helpful.

**Comment by coatless** [comment]
@kevinushey that would be great. Though, might need to enforce image size (storage + display).
