### ISSUE TITLE
JavaScript error on load

### ISSUE THREAD

**Issue by trestletech** [rstudio/learnr#315]
1. Visit https://learnr-examples.shinyapps.io/ex-setup-r/#section-install-r
2. Look at the browser console and observe a JS error like: `TypeError: e.indexOf is not a function`

This shows at least if you have a video in the lesson. I believe this is preventing the video progress tracking/restoration from working. e.g. https://rstudio.github.io/learnr/publishing.html#recording_events claims that you get events as the video progresses, and the code seems to suggest that it would restore your position in the video to where you left off. But neither of those seem to be working.

**Comment by schloerke** [comment]
https://api.jquery.com/load-event/

> Note: This API has been removed in jQuery 3.0; please use .on( "load", handler ) instead of .load( handler ) and .trigger( "load" ) instead of .load().

In regards to https://github.com/rstudio/learnr/blob/c6881a01ce13bd6a8351febce2f860245547846f/inst/lib/tutorial/tutorial.js#L372

This was caused by shiny upgrading to jQuery v3
