### ISSUE TITLE
Code block input/output not persisted

### ISSUE THREAD

**Issue by trestletech** [rstudio/learnr#318]
In the "tutorial storage" section [here](https://rstudio.github.io/learnr/publishing.html#tutorial_storage) it explains how to persist the progress/state of an application. This appears to work as expected for e.g. the selected tab or a multiple-choice question input/output. However, it's not working for code input/output. Is this by design or a bug?

Here's the sample I'm using that writes all objects out to an RDS file.
https://gist.github.com/trestletech/90f2a4062dfae97c640c35050f90c66c

I believe that the code input/output are getting saved into that RDS file, they're just not getting restored properly, it seems?

**Comment by schloerke** [comment]
Probably a bug that exercise code and exercise input are not being restored.

**Comment by trestletech** [comment]
If you do end up looking at this, one other related feature request that came up: sometimes the output of exercises can be really big (hundred+ kB) because it contains the all the HTML/JS necessary to generate a really large dataset as a table. It would be great to be able to either

1. turn off the persistence of exercise output altogether. This would be a blunt tool, but would at least prevent the state from growing out of control. Or 
2. Only capture exercise output if it's under some configurable size. So we might configure it to only capture output < 10kB but drop anything bigger than that.

I think the UX would be reasonable here. In that the code that you created is still persisted and available and you're one click away from getting the output back (just click "Run"). But if we wanted to go one step further, we could put a little message down there that says that the output wasn't persisted and that you need to click Run again if you want to see it. But I'm not even sure if that would be necessary, IMHO.

**Comment by jcheng5** [comment]
@trestletech Your `get_objects` should return an unnamed list instead of a named one, then it works.
