### ISSUE TITLE
Documentation - Tell users to not include .html tutorial files

### ISSUE THREAD

**Issue by KatherineCox** [rstudio/learnr#327]
So, I'm primarily an educator, but I've been inspired by rstudio::conf to try turning my learnr tutorials into packages so I can more easily pass them out to students and include their assets (e.g. images, data) and dependencies.

I'm getting a bit hung up on whether I need to be including or ignoring .Rmd and .html files...

- learnr documentation indicates "Render your tutorial .Rmd to .html and include the rendered HTML in your R package"  (and `learner::run_tutorial()` says something similar)
- Looking at how `usethis::tutorial()` works, it adds the .Rmd for the tutorial to `.Rbuildignore`

These seem to suggest that I should be putting the rendered .html in my package.

However,
- `usethis::tutorial()` adds the .html files to `.gitignore`, so, at least for people installing my package off of GitHub, the .html files won't be available
- the `learnr` `.Rbuildignore` file has the .html files, not .Rmd (`^inst/tutorials/.*\.html$`)
- when I install `learnr`, the .Rmd files (from the example tutorials) are what end up on my computer (and if the .html files get installed, I haven't found them)
- After some (non-exaustive) tests, including the .Rmd files and excluding the .html files seems to work just fine

Given all of this, I would conclude that I should just include the .Rmd files rather than the .html files, except the `learnr` documentation makes it sound like the wrong thing to do, and I'm inclined to listen since I'm new to this.

It sounds like there was some discussion of this in conjunction with `usethis` (https://github.com/r-lib/usethis/issues/782), so it may just be that `learnr` documentation needs updating?  At any rate, I'd appreciate some clarity on what should be included in my package and what exactly I should add to my `.gitignore` and `.Rbuildignore` files.

If this is a `learnr` documentation issue, perhaps merge with https://github.com/rstudio/learnr/issues/254?

**Comment by schloerke** [comment]
@KatherineCox You are correct.  It is a `learnr` documentation issue. 

Please ignore the `.html` tutorial files.  

-------------------

Context: The original belief was that by including the html files within the R package, users would not have to compile the tutorial, only run it.  However, we ran into many issues.  Mainly that your R session will most likely never match the user's R session after package creation as some dependency package will probably be updated.  With the package version mismatch, unexpected problems can occur.
