### ISSUE TITLE
Add-Comic Like User-Friendly Drawings: To make learning more enjoyable

### ISSUE THREAD

**Issue by jtelleriar** [rstudio/learnr#338]
Add-Comic Like User-Friendly Drawings: To make learning more enjoyable

Eg:

https://stats.stackexchange.com/questions/423/what-is-your-favorite-data-analysis-cartoon

**Comment by profandyfield** [comment]
You can include figures in the usual way. Put them in a folder images and use standard markdown. eg to include my_figure.png:

![Figure x: my caption](./images/my_figure.png)
