### ISSUE TITLE
Documentation: Links to individual examples are broken

### ISSUE THREAD

**Issue by batpigandme** [rstudio/learnr#342]
On the [Examples page](https://rstudio.github.io/learnr/examples.html) of the documentation, the **Source** link to the "summarizing data" example below the image seem to be broken. 

Currently the link goes to: https://github.com/rstudio/learnr/tree/master/inst/tutorials/ex-data-summarise/ex-data-summarise.Rmd

I believe the correct link is: https://github.com/rstudio/learnr/blob/master/inst/tutorials/ex-data-summarise/ex-data-manip-summarise.Rmd

From what I can tell, the examples and their links are generated here, so I'm not totally sure where to make the fix:
https://github.com/rstudio/learnr/blob/a2f98790423b5a96d8468aba025273f977fe5716/docs/examples.Rmd#L16-L18

**Comment by schloerke** [comment]
Great catch! Thank you!
