### ISSUE TITLE
Copy tutorial folder to temp folder when calling `run_tutorial`

### ISSUE THREAD

**Issue by schloerke** [rstudio/learnr#347]
See https://github.com/rstudio/rstudio/issues/6583

Paraphrasing...

> `learnr` attempts to render the `learnr` document directly in the installed package's folder. We need to check for write permissions and instead copy + run within the R temporary directory (since `learnr` + `learnr`-using packages might be installed into an R library that the running user doesn't have write access to)

cc @kevinushey @trestletech

**Comment by bhogan-mitre** [comment]
Could this be as simple as passing `render_args <- list(output_dir = tempdir())` as argument to [`rmarkdown::run`](https://github.com/rstudio/learnr/blob/master/R/run.R#L60)?  

Here's a [commit](https://github.com/bhogan-mitre/learnr/commit/14510dc4375d52a666a2b2b35051e3e1073d6afa) that does that.

For example, with `run_tutorial("slidy", "learnr")`, that produces:

```
Output created: /tmp/RtmpYSUQAT/slidy.html
```

**Comment by bhogan-mitre** [comment]
Actually this needs a bit more work in the intended environment (system library with unprivileged user).
```
Error in file(con, "w") : cannot open the connection In addition: Warning message: In file(con, "w") : cannot open file 'slidy.knit.md': Permission denied
```

I will try to clean it up and submit a PR if I can confirm it's working properly.

**Comment by bhogan-mitre** [comment]
Okay, I did get this to work as intended as an unprivileged user with `learnr` in the system library.

```
processing file: slidy.Rmd
...

output file: /tmp/RtmpOj37CC/slidy.knit.md
...

Output created: /tmp/RtmpOj37CC/slidy.html
```

PR forthcoming with the patch, if you're open to it.  Thanks in advance for considering.

**Comment by schloerke** [comment]
@bhogan-mitre Thank you for looking into this error!

One thing that we will want to try to do is maintain the current save location as it will exist after R shuts down / computer restart.  By always storing it as a temp file, then a lot of shiny-prerendered functionality is turned into a standard `Rmd` file.

If we could check that we have write privileges in the expected location, we should leave the Rmd output as is. If we do **not** have write privileges, setting the output to a temp dir is a great solution.

PRs are always welcome!!

**Comment by jcheng5** [comment]
Hmmm, is it _ever_ a good idea to write into a package library (other than, like, actually installing/updating/removing a package)? Seems wrong somehow!

**Comment by homerhanumat** [comment]
How is this coming along?  (For now I suppose just ask students to install the tutorial-endowed package into their User Library and use `learnr:run_tutorial()` in the Console.)

**Comment by schloerke** [comment]
@hadley Unfortunately stalled for the moment.  

-----------

Update on approach: Use a cache disk location and copy the tutorial directory, then compile in there.

Ex tutorial directory: `file.path(rappdirs::user_data_dir(), "R", "learnr", "tutorial", "package")` similar to  https://github.com/rstudio/learnr/blob/9dfe4a94fa3f8e0fa02b35fa55f9bcc0b571c49e/R/storage.R#L277

This would allow for tutorial output to persist between R sessions and not build them in the installed folder.

This cache folder could be checked for being able to write and could failover to the temp folder.
