### ISSUE TITLE
Trigger actions when student advances between sections

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#357]
I'm settling more and more on tutorials that use progressive reveal (`progressive: true` in the YAML) displayed within or alongside the IDE. When combined with functionality with the `rstudioapi` package, this provides a convenient way to teach students not just how to write code, but also how to interact with the IDE.

**For these tutorials, it would be incredibly useful to trigger code whenever a student advances from one subsection to the next.** i.e. it would be incredibly useful to provide code that is run when a subsection begins (`pre`) and/or to provide code that is run when a section ends (`post`).

Here is an example use case:

1. The student clicks the "Continue" button to move to the next subsection, which will introduce the `mpg` dataset. The subsections that follow will also discuss the `mpg` dataset. I would like to display the dataset in a way that persists as the student moves from subsection to subsection. I would also like to familiarize the student with the RStudio IDE data viewer.

2. I have provided the following code for learnr to run when the tutorial advances to the new subsection, `rstudioapi::sendToConsole("View(ggplot2::mpg)", echo = FALSE, focus = FALSE)`.  I've provided it as an R code chunk with a special label, or a special option, or I've provided it in `{` after the subsection title, or by some other documented method

3. learnr runs the code as it advances to the new subsection, which opens `mpg` in the data viewer.

**Comment by garrettgman** [comment]
We should think about implementing a system that can ensures that an action only happens once, the first time a student reaches the sub-section.

**Comment by trestletech** [comment]
I think this is already doable with the learnr event hooks. The mission would just be to wrap them up into an easily digestible format

**Comment by trestletech** [comment]
```
YAML
---

` ` `{r}
if (in_prod){
  source("eventHandlingScript.R")
}
` ` `

## Section 1

` ` `{r, echo=FALSE}
learnr::onEvent("sectionViewed", function(){
  rstudioapi::appendTextToDocument("my text here")
})

onSectionViewed("section1", function(){

})
viewedSections <- character(0)
learnr::onEvent("section1", function(){
  if ("section1" %in% viewedSections)
    return()
  viewSections <- c(viewedSections, "section1")  
  trigger("section1once")
})

learnr::oneEvent <-

` ` `

## Section 2

```
