### ISSUE TITLE
Warning when exercise gives invisible result

### ISSUE THREAD

**Issue by dtkaplan** [rstudio/learnr#369]
There's an internal function in `exercise.R` that is called when the exercise code produces an invisible result. I'm not sure why an invisible result is something you want to check for and why this feature is needed at all. @garrettgman 

I think the warning being displayed will be unfriendly to most students. Might we either

1. Allow it to be configured/disabled as an option.
2. Set it to something more friendly, like: "Note: Using assignment in the last line means that no value will be printed." Of course, you also get the warning when the last line generates a side effect but no value, e.g. `plot(1:10)`
3. Leave it to the code checking. If `last_value` is `NULL`, that might suggest a helpful hint depending on the context, but only the author of the tutorial can decide what that should be.

```r
invisible_feedback <- function() {
  feedback_as_html(
    feedback_validated(
      list(
        message = "Last value being used to check answer is invisible. See `?invisible` for more information",
        type = "warning",
        correct = FALSE,
        location = "append"
      )
    )
  )
}
```

**Comment by mine-cetinkaya-rundel** [comment]
I second this suggestion! I like options 1 and/or 3. I think a combination of the two makes sense.

**Comment by garrettgman** [comment]
I agree with @dtkaplan and @mine-cetinkaya-rundel. learnr probably doesn't intend to tell the student that their answer is invalid for learnr.

I vote for option 3. Since this is a check, we should leave it to the author and the checking package.
