### ISSUE TITLE
Using the `type = "learnr_text"` argument turns all answers incorrect

### ISSUE THREAD

**Issue by adisarid** [rstudio/learnr#375]
Using `learnr` version 0.10.1, R 3.6.3.

A minimal example for the code which recreates the bug:

````
---
title: "Tutorial"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
```

This works ok:
```{r works-ok}
quiz(
  question_text(
    "What is this great package you are using?",
    allow_retry = T,
    answer("learnr", correct = T)
  )
)
```

This one miss-behaves:
```{r miss-behaves}
quiz(
  question(
    "What is this great package you are using?",
    type = "learnr_text",
    allow_retry = T,
    answer("learnr", correct = T)
  )
)
```

````

Reading the documentation, I'm pretty sure I'm using the second chunk as intended, but maybe I misunderstood?

Here's how the output looks like (both should show a "Correct!" answer but the second variation fails:
![bug_example](https://user-images.githubusercontent.com/19262838/82952100-0b8c6700-9fb1-11ea-87c4-75ad1fc841e5.png)

**Comment by schloerke** [comment]
Great find!  Thank you for the small reprex!
