### ISSUE TITLE
exercise.warn_invisible

### ISSUE THREAD

**Issue by deepanshu88** [rstudio/learnr#378]
**exercise.warn_invisible** is not working. I reinstalled learnr package from github ( Version: 0.10.1.9004
.

`tutorial_options(exercise.checker = gradethis::grade_learnr, exercise.warn_invisible = FALSE)`

It is returning error - unused argument

**Comment by nischalshrestha** [comment]
You're receiving that error because `exercise.warn_invisible` has not yet been incorporated into learnr. The option will be available soon with PR https://github.com/rstudio/learnr/pull/373.

**Comment by cpsievert** [comment]
Should be working now if you `remotes::install_github("rstudio/learnr")`
