### ISSUE TITLE
How could i translate some button labels in french

### ISSUE THREAD

**Issue by ericemc3** [rstudio/learnr#388]
For instance in exercises

Run code
Submit Answer
Start Over
Solution

**Comment by anna-doizy** [comment]
Hello,

For now, these texts seem to be written directly in the tutorial.js javascript. You can access it in learnr>lib>tutorial folder.
I don't know if translations will be implemented later.

**Comment by ColinFay** [comment]
A good way to do this would be to have a mechanism for integrating a `.po` file to translate common UI elements. 

Once implemented, this could also lead to a community effort to translate the UI in multiple languages, and share these translations inside `{learnr}`.

**Comment by eliocamp** [comment]
Here's some code to modify the tutorial.js and related files: 
https://gist.github.com/eliocamp/b2b82f9c3c622964696c5b308c9ae108

You need to modify the `text` names to whatever text you want to use for each UI element. It will modify your local javascript files and create a tutorial using those strings. I'm not sure how would it work in deployment and distribution. 

Here's it in action:

![image](https://user-images.githubusercontent.com/8617595/95020828-e46f3180-0643-11eb-85e0-179496600f79.png)


Is not complete and some strings are hard to change (`caption = "Solution";`, `caption = "Hints";` and `caption = "Hint";` are hind of hard to distinguish and change correctly). 

Also, let me link to a duplicate issue so that they are linked: https://github.com/rstudio/learnr/issues/108

**Comment by ericemc3** [comment]
very handy, thanks!

**Comment by ColinFay** [comment]
Hey y'all,

Fyi I'm currently actively working in this feature, so expect something in the upcoming weeks :)

**Comment by eliocamp** [comment]
Fantastic! Thanks!

**Comment by gadenbuie** [comment]
Support for internationalization was added in #456 with help from @ColinFay!

We currently provide English and French translations and would happily accept translations for other languages as well. If you would like to contribute a translation for your native language, please read `vignette("multilang", package = "learnr")` for instructions, or submit a PR modifying [i18n_translations()](https://github.com/rstudio/learnr/blob/6694842d8b9a74fbff92ef8a64a49adcc5a30199/R/i18n.R#L124-L146) following the example for English.

**Comment by ericemc3** [comment]
Great, thank you @gadenbuie and @ColinFay!
Just wondering how to display : `vignette("multilang", package = "learnr") `, i get a warning message

I understand i can use it this way:
```
output: 
  learnr::tutorial:
    progressive: true
    language: fr
runtime: shiny_prerendered
```

**Comment by gadenbuie** [comment]
@ericemc3 Can you confirm that you updated the learnr package to the latest development version? You'll need to run 

```r
devtools::install_github("rstudio/learnr")
```

**Comment by ericemc3** [comment]
yesy i did, and my learnr version is 0.10.1.9007

Anyway i was able to compile with language: fr and get buttons labelled in french, so i am satisfied, even if i don't get the vignette

**Comment by eliocamp** [comment]
`install_github()` doesn't build vignettes by default. You should install with 
```r
devtools::install_github("rstudio/learnr", build_vignettes = TRUE)
```

I'm having no problem accessing the vignette after installing the package that way.

**Comment by ericemc3** [comment]
That's it indeed, i can now load the vignette, thanks!

**Comment by gadenbuie** [comment]
@ericemc3 great! Thanks @eliocamp for filling in the `build_vignettes = TRUE` detail!

**Comment by yabellini** [comment]
I was able to translate into Spanish by following the instructions in the bullets with no problem.  I can't find how to translate the buttons: "Next Hint" and "Copy to Clipboard" appearing in the exercise code box.

**Comment by ericemc3** [comment]
Indeed, i can't see them translated in French either, they might have been forgotten in tutorial.js

**Comment by ericemc3** [comment]
There are also the "R code" caption, and tootips attached to the buttons that are not translated

**Comment by gadenbuie** [comment]
> I was able to translate into Spanish by following the instructions in the vignettes with no problem.  I can't find how to translate the buttons: "Next Hint" and "Copy to Clipboard" appearing in the exercise code box.

Thanks for letting me know and for the translation @yabellini! I'll add them next week and follow up with you in your PR. We need "Solution", too.

@ericemc3 if you reply with the French translation for these I'll incorporate them.

**Comment by yabellini** [comment]
Awesome! Thank you! Here is the Spanish version:
Next Hint = "Siguiente sugerencia"
Copy to Clipboard = "Copiar al portapapeles"
Solution = "Solución"
R code = "Código R"

**Comment by ericemc3** [comment]
Thanks a lot @gadenbuie. Here are the french complements:
Next Hint = "Indice suivant"
Copy to Clipboard = "Copier dans le presse-papiers"
Solution = "Solution"
R code = "Code R"

'hints' label should be plural, as in english
hints = "Indices"
