### ISSUE TITLE
Global option to show/hide solution 

### ISSUE THREAD

**Issue by mine-cetinkaya-rundel** [rstudio/learnr#402]
Currently, an exercise chunk will show the model solution if a chunk with `-solution` is provided. If you have hints, you scroll through all fo them and then the solution is shown.

I would love to be able to set some global option which, if set to `FALSE`, will show the hints but not the model solution, and if set to `TRUE`, it will show it. This would allow me to develop the learnr tutorial with the solution chunks in place, hide them until a deadline, and then redeploy with the option turned on to show the solutions. 

I realize that right now I can achieve this result by going back after the deadline and adding the solution chunks in (or uncommenting them), but it would be nice to write the whole tutorial at once and then just flip a switch later.

**Comment by davidkane9** [comment]
I would make use of this option as well.

**Comment by ColinFay** [comment]
Current hacky way to do that for anyone passing by: 

Append:

```javascript
<script>
$(function(){
  $('a[title="Solution"]').remove()
})
</script>
```

to the end of the Rmd

**Comment by garrettgman** [comment]
Can we expedite this issue? We're writing more sophisticated grading code that requires the author to provide a solution to each exercise, but we'd usually prefer not to make the solutions accessible to the students.
