### ISSUE TITLE
Error Sound

### ISSUE THREAD

**Issue by pseudorational** [rstudio/learnr#409]
It would be nice to have an sound to alert users when they make an error in a Quiz Question. Similarly, a celebratory sound if they get it correct. 

I tried using beepr::beep() to create a sound for an incorrect answer. But, the following code throws up an error

```{r setup, include=FALSE}
library(learnr)
knitr::opts_chunk$set(echo = FALSE)
library(beepr)
```

```{r q2_quiz, echo=F}
quiz(caption='',
  question("Compute trigonometric tangent for an angle of 45 degrees?",
           answer("1",correct = F),
           answer("1.619775", correct=F),
           answer("2", correct = T),
           answer("-1.9952",correct = F),
           allow_retry = T,
           incorrect = rep(beep(2),4)
  )
)
```

**Comment by schloerke** [comment]
Neat idea, but I don't think it'll work in practice.  When tutorials are hosted, the R environment is not within the browser.  So the beep may play, but it'll play on the server, not in the browser.

We might be able to make a custom question type that makes a sound when `question_is_correct` is called. But this _might_ only work when running tutorials locally.  

There is also issues with `beepr` not producing noise when running in a background / non-interactive R session (which is what the IDE likes to do). 

```r
# makes a noise
beepr::beep(2)

# doesn't make a noise
callr::r(function() {
  beepr::beep(2)
})
```

**Comment by pseudorational** [comment]
Thank you. By the way, the suggestion came from my 10 year old son, Rohan!

**Comment by schloerke** [comment]
```r
rohan <- beepr::beep(8)
```
