### ISSUE TITLE
'Empty' exercise chunks aren't treated as exercises

### ISSUE THREAD

**Issue by cpsievert** [rstudio/learnr#410]
Running the tutorial below yields a misleading error of:

```r
Error in is_code_identical(user, solution) : 
  No solution is provided for this exercise.
```

This is because the `foo` chunk isn't being treated as an exercise, so the `foo-check` is being evaluated outside of a `grade_learnr()` context. Adding an empty line to the `foo` chunk fixes the problem, but either a more informative error should be thrown, or it should "just work"

````
---
title: "Issue #410"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
tutorial_options(exercise.checker = grade_learnr)
knitr::opts_chunk$set(echo = FALSE)
```

## Minimal example

This chunk isn't treated as an exercise!

```{r foo, exercise = TRUE}
```

```{r foo-solution}
sum(1)
```

```{r foo-check}
grade_code()
```
````

**Comment by KatherineCox** [comment]
Is this related to #172 ?
