### ISSUE TITLE
`learnr::run_tutorial()` multiple times in a single session "breaks" exercises

### ISSUE THREAD

**Issue by agmath** [rstudio/learnr#419]
Hello,

If I run `learnr::run_tutorial()` to render an interactive `learnr` notebook in an R session, the first notebook renders correctly. If I close that notebook, stop the running process by hitting the console's stop sign icon, and then attempt to re-run a second notebook with another call to `learnr::run_tutorial()` then `learnr` does not render any of the *exercise* chunks in the new notebook correctly. I am able to render the notebook as expected if I:
1. Go through my file manager and remove the rendered html file and then
2. Re-open RStudio and launch the notebook with `learnr::run_tutorial()` 

I should note that launching multiple pre-rendered notebooks with `learnr::run_tutorial()` in a single R session does not cause any of these errors. I suspect this is since those documents were rendered in a prior R session. 

Now that I know this, I am able to avoid the issue or correct it relatively easily. I am planning to use `learnr` notebooks with first-year University students though, and I am not so optimistic about being able to help them troubleshoot this issue. Have any of you also run into this problem? Is there a convenient workaround? It seems that simply running `rm(list = ls())` before a second call to `learnr::run_tutorial()` is not sufficient.

Thanks!

**Comment by soniamitchell** [comment]
We're running a course right now and 2 of the 50+ students have encountered this problem. The solution we have is to reinstall rmarkdown, as well as the packaged learnr tutorials before running a new tutorial. Did you find a more elegant solution @agmath?

**Comment by agmath** [comment]
@soniamitchell   -- I have a couple.

- If students use the `tutorials` tab in the top-right pane of RStudio, then it seems as though they can launch as many tutorials as they like within a single R Session. There are no compiling errors. I don't love this solution because then they are running the tutorials from a small pane within RStudio. That being said, this seems to be the easiest solution to implement.
- When students encounter this issue with me now, I ask them to run `find.package("AppliedStatsInteractive")`, the name of the package they are using. We then navigate to that location on their computers and delete the `*.html` file that was generated. Once that file has been removed, recompiling with `learnr::run_tutorial()` seems to work just fine.

I hope this helps!

**Comment by gadenbuie** [comment]
@agmath Have you been able to reproduce the issue yourself? I'm wondering if you can give any more hints about when or how it's happening.

Another idea to try: instead of navigating to and deleting the `.html` file, if you have the file path, you should be able to accomplish the same thing by running `rmarkdown::shiny_prerendered_clean("path/to/your_tutorial.html")`.

**Comment by agmath** [comment]
@gadenbuie I think this is what you are asking for, but please let me know if that is not the case:

- I wrote a package of course notes for use in an introductory statistics course. I have students install the package with `remotes::install_github("agmath/AppliedStatsInteractive")` -- the package just consists of a series of `learnr` tutorials.
- If students click the `Start Tutorial` button in RStudio's `tutorials` tab, then there don't seem to be any challenges, regardless of the number of notebooks they open in a single session.
- Originally, I didn't know about the `tutorials` tab and so I suggested students run the notes by running `learnr::run_tutorial()`
    - If they run, for example `learnr::run_tutorial("2_IntroToR", package = "AppliedStatsInteractive")`, then the notebook renders fine and opens in a browser tab as expected.
    - If the student then wants to open a second set of notes, and runs `learnr::run_tutorial("4_DataViz", package = "AppliedStatsInteractive")` in the same R Session (after disconnecting from the initial notebook), the behavior used to be that the `html` file was built, but the interactive code blocks didn't render -- in their place seemed to be the code needed by `gradethis` to check the student's input. Now I am noticing something different.
    - The second notebook no longer renders. Instead I get an error that looks like it is being thrown from the `gradethis` package: 

```
Quitting from lines 102-103 (4_DataViz.rmd) 
Error in is_code_identical(user, solution) : 
  No solution is provided for this exercise.
```

Closing RStudio (or restarting the R Kernel) and re-running the `learnr::run_tutorial()` command with the desired notebook then runs and renders the notebook as expected. That being said, it seems as though there is no longer a need to navigate to and remove the `html` file after this error since it is not being built. While the error is still inconvenient, this seems to be much easier to troubleshoot with students. (These issues only occur with notebooks whose `html` files have not been previously built)

I know that `learnr` and `gradethis` were both recently updated, but the issue could also be with my package (this was my first attempt at writing a package). It seems to me like the issue comes from `gradethis` though. I hope this helps!

**Comment by gadenbuie** [comment]
I've occasionally seen something similar, and as far as I can tell it generally means that there's an issue with the tutorial itself (a missing exercise-related chunk argument or a misspelled chunk label) or it means that the tutorial was rendered in a different environment. 

I think that the second is most relevant to you, @agmath. In particular, it's best not to include any of the transient files that are created when you render your tutorial, such as the `.html` file or the `_files` folder. This will ensure that the tutorial is completely rendered on the student's machine and matches their package versions, etc. In other words, I would try removing `4_DataViz.html` and `4_DataViz_files/` from the [4_DataViz tutorial folder](https://github.com/agmath/AppliedStatsInteractive/tree/master/inst/tutorials/4_DataViz).

FYI, for reference, this advice is embedded in point 2 under the "R Package" section of the Publishing page on the learnr docs: https://rstudio.github.io/learnr/publishing.html#R_Package

@soniamitchell Does this seem relevant to your tutorial issues also? If you can share a link to your tutorials, I'll be happy to investigate.

**Comment by soniamitchell** [comment]
Hi @gadenbuie we don't have any `.html` files lying around.. but there may well be a missing/misspelled chunk! I'll investigate. Our tutorials live [here](https://github.com/IBAHCM/RPiR/tree/master/inst/tutorials) by the way.

**Comment by soniamitchell** [comment]
Hi @gadenbuie. No need to investigate, I've identified the problem. Thanks both for your help!
