### ISSUE TITLE
How to deploy a tutorial from a package on shinyapps when tutorial depends on the package the tutorial is in?

### ISSUE THREAD

**Issue by Athanasiamo** [rstudio/learnr#424]
Hi

I'm developing learnr materials for my Uni, and am so far enjoying the process. 
I've wanted to show colleagues what I have made so far, but am hitting an issue due to how we've set up the materials so far.

We are developing this as if it were a package, and this tutorials are in `inst/tutorials` . We have data-sets for the students to use stored as expected for a package, lazy-loaded and documented. This works really well in local versions where the package is installed as an actual package. 

However. when deploying to shinyapps.io, we hit a snag. The materials are on a Github Enterprise server, so we can't see to figure out how to get the package installed at the same time as a tutorial within it is being deployed. 

Any suggestion is much welcome!

**Comment by Athanasiamo** [comment]
Hi Danny.

Thanks for the feedback. This sounds like a solution I would use if I had the materials in a private standard github repo. 
But the enterprise solution we have there is no real "public" repo (i.e. even repos that are public are only public to those within the organisation), so I cannot use your workaround :/

**Comment by gadenbuie** [comment]
Unfortunately, shinyapps.io needs to be able to install the package itself. As @dtkaplan points out, this means that shinyapps.io needs to be able to reach a public endpoint to install the package. It may be possible to link your shinyapps.io account to the GHE location — this [RStudio community post](https://community.rstudio.com/t/cant-use-package-from-private-github-repo-in-shinyapps-io-app/38800) may provide some hints — but I'm not certain. You may be able to find more information in the [shinyapps.io user guide](https://docs.rstudio.com/shinyapps.io/).
