### ISSUE TITLE
exercise.error.checker should pass through error messages on Run Code

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#425]
When the tutorial option `exercise.error.checker` is set, learnr returns an unintelligible error when a student runs bad code. Here is an example. This happens when the student clicks Run Code.

<img width="1676" alt="Screen Shot 2020-08-27 at 9 44 16 AM" src="https://user-images.githubusercontent.com/85014/91450698-94ce6680-e84a-11ea-8277-ca30f80f31a8.png">

When this option is removed, learnr displays the correct, intelligible error message when the student clicks Run Code. This is the error message you would get if you run this code at the command line.

<img width="1676" alt="Screen Shot 2020-08-27 at 9 44 38 AM" src="https://user-images.githubusercontent.com/85014/91450748-a283ec00-e84a-11ea-822a-64ec6c5532a4.png">

This may be a gradethis bug. It is clear that `gradethis::grade_learnr_error` is related to the behavior, but it is unclear if `gradethis::grade_learnr_error` should be invoked when the student clicks Run Code. See https://github.com/rstudio-education/gradethis/issues/140.

Demo .Rmd:

````
---
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
library(gradethis)
library(tidyverse)

tutorial_options(
  exercise.checker = gradethis::grade_learnr,
  exercise.error.checker = gradethis::grade_learnr_error
)
```

## Aesthetics

### 

Map the chape aesthetic to a continuous variable. What happens?

```{r cty3, exercise = TRUE, exercise.eval = FALSE}
# Map cty to shape
ggplot(data = mpg, mapping = aes(x = displ, y = hwy)) + 
  geom_point()
```

```{r cty3-solution}
# Map cty to shape
ggplot(data = mpg, mapping = aes(x = displ, y = hwy, shape = cty)) + 
  geom_point()
```

```{r cty3-code-check}
grade_code("ggplot2 will map shapes to discrete variables, but not continuous variables; but that makes sense: shapes are discrete. Click Run Code to see the error message that you'll get when you map shapes to a continuous variable.")
```

````

**Comment by cpsievert** [comment]
Ahh, good catch, I think should be considered a learnr issue.
