### ISSUE TITLE
silent failure if no orchestrator present

### ISSUE THREAD

**Issue by gvwilson** [rstudio/learnr#448]
1. Load `library(gradethis)` but do _not_ call `gradethis::gradethis_setup()`.
2. Write an exercise check using `grade_result()`.
3. Run the tutorial.

Learners can run the code for that exercise, but when they press `Submit code`, nothing happens. According to @schloerke this is because no orchestrator has been set up. Some sort of error message should pop up in this case telling the lesson author to initialize things.

**Comment by gadenbuie** [comment]
`library(gradethis)` automatically calls `gradethis_setup()`, so authors would now need to go through a lot of manual trouble to arrive at this situation.

That said, we should still throw an error during the pre-render step. If we arrive at a `-check` chunk we can check that an `exercise.checker` has been defined and throw an error if one does not exist.
