### ISSUE TITLE
Warning in selectChildren(jobs, timeout)

### ISSUE THREAD

**Issue by tombeesley** [rstudio/learnr#449]
When this minimal example is distributed on shinyapps.io, the logs report a warning every time an action is executed (i.e., clicking Run Code). I'm wondering if this is anything to worry about? I'm getting frequent disconnects on some learnr tutorials with a class of ~30 and shinyapps support noted this as a potential cause.

Error is:

2020-11-12T21:13:29.016157+00:00 shinyapps[3220841]: Warning in selectChildren(jobs, timeout) :
2020-11-12T21:13:29.024664+00:00 shinyapps[3220841]: sh: 1: kill: No such process
2020-11-12T21:13:29.016160+00:00 shinyapps[3220841]:   cannot wait for child 120 as it does not exist

````rmd
---
title: "test"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
---

```{r setup, include=FALSE, exercise.startover = TRUE}
library(learnr)

knitr::opts_chunk$set(echo = FALSE)
```

```{r summary_example, exercise=TRUE}
print("blah")
```

````

**Comment by schloerke** [comment]
From what I understand, it is not something to worry about. 

When the evaluator process is being set up, if the code is short (Ex: `Sys.time()`) then it is finishing faster than learnr can check on it. I believe this is a verbose bug within `parallel::mccollect()` with `wait = FALSE` claiming that it can not collect information from a process that does not exist. ... even though we are collecting the returned value.

@trestletech Does this seem correct?

**Comment by tombeesley** [comment]
Thanks @schloerke - good to know this isn't causing the disconnects. I guess we need to figure out how to configure our instances/workers/connections.

**Comment by schloerke** [comment]
Give this a shot first: https://cran.r-project.org/web/packages/learnr/vignettes/shinyapps-publishing.html
Hope this helps!

**Comment by tombeesley** [comment]
That's super useful. thanks!

**Comment by schloerke** [comment]
Closing for now
