### ISSUE TITLE
Running tutorial fails due to `path.expand()` error

### ISSUE THREAD

**Issue by mpjashby** [rstudio/learnr#471]
A student trying to run learnr tutorials in the current stable release of RStudio and the current release of R is getting the following quite generic error message. They also get the same message while trying to run learnr tutorials from other packages. This was immediately after installing R, RStudio and the learnr package all for the first time. I cannot reproduce this on my computer (macOS) or another computer with Windows 10. 

I'm hesitant to post the reprex below because it doesn't seem to provide much information, but looking at the R code for `run_tutorial()` and `get_tutorial_path()` doesn't provide any obvious (to me at least) potential solutions, so I'm at a loss as to what else to do.

``` r
learnr::run_tutorial("ex-data-basics", package = "learnr")
#> Error in utils::shortPathName(path.expand(path)): 無效的多位元組字串於 '<e6><96><87>隞<b6>/R/WIN-LI~1/4.0/learnr/TUTORI~1/EX-DAT~1'
```

<sup>Created on 2021-01-13 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

<details>

<summary>Session info</summary>

``` r
sessionInfo()
#> R version 4.0.3 (2020-10-10)
#> Platform: x86_64-w64-mingw32/x64 (64-bit)
#> Running under: Windows 10 x64 (build 18363)
#> 
#> Matrix products: default
#> 
#> locale:
#> [1] LC_COLLATE=Chinese (Traditional)_Hong Kong SAR.950 
#> [2] LC_CTYPE=Chinese (Traditional)_Hong Kong SAR.950   
#> [3] LC_MONETARY=Chinese (Traditional)_Hong Kong SAR.950
#> [4] LC_NUMERIC=C                                       
#> [5] LC_TIME=Chinese (Traditional)_Hong Kong SAR.950    
#> 
#> attached base packages:
#> [1] stats     graphics  grDevices utils     datasets  methods   base     
#> 
#> loaded via a namespace (and not attached):
#>  [1] Rcpp_1.0.5         knitr_1.30         magrittr_2.0.1     xtable_1.8-4      
#>  [5] R6_2.5.0           rlang_0.4.10       fastmap_1.0.1      stringr_1.4.0     
#>  [9] highr_0.8          tools_4.0.3        xfun_0.20          withr_2.3.0       
#> [13] htmltools_0.5.0    rprojroot_2.0.2    yaml_2.2.1         digest_0.6.27     
#> [17] shiny_1.5.0        later_1.1.0.1      htmlwidgets_1.5.3  promises_1.1.1    
#> [21] curl_4.3           evaluate_0.14      mime_0.9           rmarkdown_2.6     
#> [25] stringi_1.5.3      compiler_4.0.3     learnr_0.10.1.9007 jsonlite_1.7.2    
#> [29] renv_0.12.5        markdown_1.1       httpuv_1.5.4
```

</details>

**Comment by schloerke** [comment]
Don't know if related to #211 or #314 . 

I don't think so as this error is happening on macOS where as those are happening only on Windows (and probably due to Windows's file path limit of ~260 characters).  

Possibly an encoding issue as `無效的多位元組字串於` translates to `Invalid multi-byte string in`

**Comment by schloerke** [comment]
@mpjashby What would you expect to have for the full path name? It looks like some of the path was not converted correctly. Thank you
