### ISSUE TITLE
navigate through hints (forward and backward)

### ISSUE THREAD

**Issue by ericemc3** [rstudio/learnr#478]
When multiple hints are available,
i can go to the next one ("Next hint") but i can't go back ("Previous hint" ?)
Even if i close hints, or reinit the exercise, if i click the "hints" button again, only the last hint i viewed is displayed, 

I have to start over the whole tutorial to access these previous hints

**Comment by gadenbuie** [comment]
Thanks @ericemc3, this is on our radar for future updates. We're tracking progress on this feature in #115.

**Comment by ericemc3** [comment]
Thnaks, sorry for the dupe!
