### ISSUE TITLE
is "exercise.timelimit" working?

### ISSUE THREAD

**Issue by ltl-manabi** [rstudio/learnr#492]
Hi, I'm using exercise chunk for database access. This takes little long time. So, I'm setting the "exercise.timelimit" option to 180 seconds. But over 30 seconds, chunk has stopped and the message "Error: Your code ran longer than the permitted timelimit for this exercise." appears.

I'm setting option to chunk or header, either same.

There is minimal example. I'm using newest version of learnr package from GitHub.

<pre>
```{r ex1, exercise=TRUE, exercise.timelimit=180}
# This chunk should stop after 30 seconds.
Sys.time()
Sys.sleep(60)
Sys.time()
```
</pre>

How do I set correct time limit? Thanks.

**Comment by schloerke** [comment]
Thank you @ltl-manabi !
