### ISSUE TITLE
Adjust tutorial template for correct ordering of dependency loading

### ISSUE THREAD

**Issue by johnbde** [rstudio/learnr#499]
In google chrome console window, it shows "ReferenceError: $ is not defined". I guess it is because the script below loads before jquery. I am using latest version of rmarkdown which fixed Invalid HTML code.  PS - It also could not find favicon.

```
$(document).ready(function () {
--
  | window.buildTabsets("section-TOC");
  | });

```

````

---
title: "Hello, Tutorial!"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
```

This code computes the answer to one plus one, change it so it computes two plus two:

```{r addition, exercise=TRUE}
1 + 1
```

````

**Comment by gadenbuie** [comment]
We'll need to update the learnr tutorial template in line with the changes from https://github.com/rstudio/rmarkdown/pull/1942 or we'll wait to see if this is resolved upstream in rmarkdown.
