### ISSUE TITLE
Pagination

### ISSUE THREAD

**Issue by johnbde** [rstudio/learnr#500]
Does output support pagination (like datatable library)? I am using `max.print` to limit rows, would be helpful if output having large no. of rows can be split over multiple pages.

**Comment by gadenbuie** [comment]
You can use the [`df_print` argument](https://bookdown.org/yihui/rmarkdown/html-document.html#data-frame-printing) to print tables as paged tables:

```
---
#... yaml header ...
output:
  learnr::tutorial:
    df_print: paged
---
```

**Comment by markwsac** [comment]
Thank you. Actually I am using this `df_print: paged` only. I just realized it works with r chunk but not with SQL.

```
con <- DBI::dbConnect(RSQLite::SQLite(), "mydb.sqllite")

```{sql q1, connection="con", exercise=TRUE}
SELECT * FROM table1 LIMIT 5
```

```

**Comment by johnbde** [comment]
Thank you. Actually I am using this df_print: paged only. I just realized it works with r chunk but not with SQL.

```
con <- DBI::dbConnect(RSQLite::SQLite(), "mydb.sqllite")

```{sql q1, connection="con", exercise=TRUE}
SELECT * FROM table1 LIMIT 5
```
