### ISSUE TITLE
Time taken to load JS and CSS files

### ISSUE THREAD

**Issue by markwsac** [rstudio/learnr#502]
It takes a good amount of time to load view-source of the learnr doc which indicates some issues with loading JS, CSS or HTML files. Background - Sometimes when user clicks on "Run Code" button , it keeps on running and does not return output but event recorder captures correctly all the info (including code) - "label", "question", "answer", "code". It does not stop in 30 seconds even when you set `exercise.timelimit = 30`. I figured out a weird way to workaround this issue - If I click on "Next Topic" and then comes back to the question in which i hit "Run Code" button, it returned output of that question. It seems some issues with javascript. Thanks in anticipation.

`R version 3.6.1 (2019-07-05)
 "Windows"       "10 x64"  "build 18363"

> packageVersion("learnr")
[1] ‘0.10.1.9008’
> packageVersion("rmarkdown")
[1] ‘2.7.2’
> packageVersion("shiny")
[1] ‘1.6.0’

`

**Comment by gadenbuie** [comment]
I think that it's possible your issue will be resolved with #503. Can you please install that version of learnr and try again?

```r
remotes::install_github("gadenbuie/learnr@template")
```

If that doesn't resolve the issue, can you please provide a [complete, minimal and reproducible example](https://reprex.tidyverse.org) that I can use to investigate further?
