### ISSUE TITLE
Disable rerun of code execution at application start-up

### ISSUE THREAD

**Issue by mstackhouse** [rstudio/learnr#508]
My team has searched around to see if this is possible, but we don't think it is.

Currently, when you open a learnr application, each of the exercise blocks executes to restore the results from the last session. When a learnr application gets larger, this can become quite intensive - particularly if the application will be used in a larger environment with a shared external evaluator, and in turn cause exercise chunks to hang while waiting for others' code to finish.

An ideal scenario would be to restore the code executed to the exercise chunk, but not rerun the exercise itself.

**Comment by gadenbuie** [comment]
I added a `tutorial.quick_restore` global option (also settable via the env var `TUTORIAL_QUICK_RESTORE`) that modifies the restore behavior when `TRUE` (or `1` for the env var). When enabled, the last submission code is restored to the exercise, but that code is not evaluated. This speeds up restore considerable, especially if any of those exercises take considerable time to evaluate.

A side-effect of the current implementation of the quick restore method is that stored previous exercise _output_ isn't restored. Users will have to click **Run Code** or **Submit Answer** to explicitly see the exercise output. I have another version of this same feature in a branch at [gadenbuie/learnr@quick-restore-2](https://github.com/gadenbuie/learnr/tree/quick-restore-2) that will use the stored output (if any). 

Where and how previous output is stored depends on your setup. @mstackhouse, Would you be able to test the [quick-restore-2](https://github.com/gadenbuie/learnr/tree/quick-restore-2) version and see if that also works in your case? It'd be nice to be able to restore previous feedback, if its available and if that doesn't add too much overhead at tutorial load.

**Comment by mstackhouse** [comment]
@gadenbuie Sure! We'd be happy to! 

I do want to confirm that tutorial.quick_restore works - we've tested that implementation out already when you pushed yesterday.

**Comment by elimillera** [comment]
Hey @gadenbuie, Thanks for the update! Can you give a short reprex I can test this with? I'm not sure in what cases the output is stored but we are currently using the default tutorial storage option.

**Comment by yassinza** [comment]
Hi @gadenbuie, we are building some large tutorials, and quick_restore, where the output is saved, would be great to have!
Anything I can help with here to being this back to life? Thank!

**Comment by gadenbuie** [comment]
Good news @yassinza, the quick restore feature was released! Check out https://github.com/rstudio/learnr/pull/509 for details.

**Comment by yassinza** [comment]
Thanks @gadenbuie! We are using this one already, but we were wondering about the quick-restore-2 you mentioned above. Do you have plans to make that available? I think it is a great feature to have for large tutorials like the ones we are building. Thanks a lot for the package btw, it is amazing!

**Comment by gadenbuie** [comment]
> I tested it, and it works as expected. The only thing missing is the Submit Answer feedback, if any.

@yassinza Unfortunately, this isn't something that we currently save in the tutorial storage.
