### ISSUE TITLE
Issue in exercise.timelimit

### ISSUE THREAD

**Issue by markwsac** [rstudio/learnr#511]
Thanks for this lovely package. I found sometimes code keep on running and does not return output. It's not with the high computation. It happens even when you have small dataset and simple data wrangling task. Code should respect `exercise.timelimit` and breaks when it exceeds. 

I found it's with  `.topics .section.level2 { }` `.topics .section.level2.current { }` If you set it `display : none;` at the start of application (let's say you are building login screen so that does not want to show tutorial at the start). Later when user is logged in if you change it via JS. It works sometimes but when user toggles between two different topics via **Next Topic** code execution keeps on continuing and does not return output, then if you click on **Next Topic** and then immediately come back to the previous topic by clicking on "Previous Topic" button it returns output.

```
  var CONTROL_INTERVAL4 = setInterval(function(){
        $('.topics .section.level2').hide();
        $('.topics .section.level2.current').show();
  }, 0);
```

**Comment by gadenbuie** [comment]
Thanks for your report. I think it's possible that exercise execution is limited to the expected time limit and that the custom JavaScript you're using for the login screen is interfering with the shiny exercise output, creating the appearance of unbounded execution. If you could please post a complete, minimal reproducible example I'd be happy to investigate further.

**Comment by markwsac** [comment]
Thanks for your response. Please find the complete minimal reproducible example. If you jump to "Boolean operators" section and come back to "Filter rows" topic, code will keep running and does not return output.

```
---
title: "Filter observations"
output: 
  learnr::tutorial:
    progressive: true
    allow_skip: true
runtime: shiny_prerendered
description: >
  Learn how to filter observations in a data frame. Use `filter()` to extract
  observations from a data frame, and use `&`, `|`, and `!` to write logical
  tests.
---

```{r setup, include=FALSE}
library(learnr)
library(tidyverse)
library(nycflights13)

tutorial_options(exercise.timelimit = 30)
options(tutorial.storage = "none", tutorial.quick_restore = TRUE)
knitr::opts_chunk$set(error = TRUE)
```

```
## Filter rows with `filter()`

### filter()


```{r filter1, exercise = TRUE, exercise.eval = FALSE}
filter(flights, month == 1, day == 1)
```
```
## Boolean operators

### Test Your Knowledge

```{r logicals, echo = FALSE}
question(" What will the following code return? `filter(flights, month == 11 | month == 12)`",
         answer("Every flight that departed in November _or_ December", correct = TRUE),
         answer("Every flight that departed in November _and_ December", message = "Technically a flight could not have departed in November _and_ December unless it departed twice."),
         answer("Every flight _except for_ those that departed in November or December"),
         answer("An error. This is an incorrect way to combine tests.", message = "The next section will say a little more about combining tests."),
         allow_retry = TRUE
)
```

```{r echo=FALSE, results='asis'}
cat("

<style>
.topics .section.level2 { display: none;}
.topics .section.level2.current { display: none;}
.topicsList {display: none;}
</style>

<script>

$(document).ready(function() {

var CONTROL_INTERVAL4 = setInterval(function(){
      $('.topicsList').show();
      $('.topics .section.level2').hide();
      $('.topics .section.level2.current').show();
}, 20);

});

</script>

")

```
```

**Comment by gadenbuie** [comment]
First, as a baseline, please make sure you're using the latest versions of learnr and rmarkdown.

I can reproduce this using the custom CSS and JavaScript, but I haven't been able to pinpoint the problem exactly. My hunch is that setting `display: none` on elements that will become shiny inputs/outputs is causing the problem. I've seen problems arise in this setting before, but I can't conclusively tell you that's what is going on here. My recommendation is to find another way to add a login screen between the user and the tutorial.

I did notice that once the code hits the "running forever state", that switching back and forth between the other topic can trigger the output to update correctly.

**Comment by markwsac** [comment]
Thanks for your response. I will work on another way to add login screen between user and tutorial. By any chance, can we measure time spent in "running forever state" and break if it exceeds `exercise.timelimit` ?
`

**Comment by gadenbuie** [comment]
It only appears to be running the exercise when in fact the exercise was evaluated quickly. The problem is that the result of the evaluation isn't correctly received by the browser, so the UI itself stays in "executing" mode, even though computation resolved long ago.
