### ISSUE TITLE
Feature request: Run only selected lines of an exercise chunk

### ISSUE THREAD

**Issue by petzi53** [rstudio/learnr#512]
Many times I have seen exercise chunks where a complex task is broken down into several steps. The code snippets consist of some prefilled parts and some parts with underscores to be substituted by the student's code. The following illustrating screenshot is taken from a [lesson of the OpenIntro project](https://openintro.shinyapps.io/ims-02-summarizing-and-visualizing-data-02/#section-density-plots-vs.-boxplots).

![task-with-several-steps](https://user-images.githubusercontent.com/24394304/114741748-6060d980-9d4b-11eb-9057-9043e4aedcca.png)

In those cases, where a task is broken down into several steps, it would be beneficial from an educational perspective when students could experiment and see if a part of their solution already works. At the moment, students have to cut those parts not ready for evaluation, try their solution, and then continue their work with pasting the code snippet from the clipboard to the exercise environment.  

An alternative could be to provide students with an extra empty exercise chunk as a sandbox to try their experiments.

But the easiest solution would be to run just a part of the exercise chunk as possible in RStudio by selecting code lines.

I do not know if this feature request could be implemented (easily), but it would provide a great enhancement.

**Comment by gadenbuie** [comment]
Thanks for the suggestion! Perfect timing, this also came up for me today and thankfully it was an easy feature to implement.

**Comment by markwsac** [comment]
Great.  Would it also apply to "Submit Code" as well? I meant if it submits the whole code or selected code if code is selected.

**Comment by gadenbuie** [comment]
No, _Submit Code_ will send all of the code in the exercise editor. Submitting only part of the exercise for checking would very likely lead to significant confusion for the user and the tutorial author.

**Comment by petzi53** [comment]
@gadenbuie Thank you. That was a swift reaction and a happy coincidence!
