### ISSUE TITLE
URL of GitHub repo not working

### ISSUE THREAD

**Issue by lorenzwalthert** [rstudio/learnr#526]
When I click on the URL on the side of the repo...

![Screenshot 2021-05-03 at 11 58 40](https://user-images.githubusercontent.com/10477073/116863671-eebbd300-ac06-11eb-8d6d-d01862a7e5f6.png)

... I get a error

![Screenshot 2021-05-03 at 11 58 00](https://user-images.githubusercontent.com/10477073/116863598-d3e95e80-ac06-11eb-98e0-33bcaafe3a9e.png)

I think the URL needs to be the same as in the `README`, i.e. http://rstudio.github.io/learnr/

**Comment by schloerke** [comment]
Thank you! Fixed

(Thank you for the screen shots!!)
