### ISSUE TITLE
Tutorial is greyed and blue buttons don't work

### ISSUE THREAD

**Issue by emarsh25** [rstudio/learnr#533]
I am trying to create a learnr tutorial on Rstudio. I am struggling to get any of the default tutorials to work. When I open the tutorial, it shows up, but the screen is greyed out. Also, none of the blue buttons work (i.e. run code). I am not sure if I made a mistake in my set up. Please help!

![Screenshot from 2021-06-03 16-30-38](https://user-images.githubusercontent.com/35982301/120723554-33998a80-c48f-11eb-8a65-8b67944bb62d.png)

**Comment by gadenbuie** [comment]
That appearance is typical if there's been an error serving the tutorial with Shiny, but it's hard to tell from this screenshot what the cause might be. 

In the bottom left pane of your RStudio IDE, in the **Jobs** pane, you should be able to see the console output from serving the tutorial. It's possible that the output there may provide some hints — you can copy and paste the text from that pane into a comment in this issue.

It would also be helpful if you could run `devtools::session_info()` in the R console in RStudio. Copy and paste the output and include it here in a comment as well. Both of those items will help us debug your issue further.
