### ISSUE TITLE
 Add option to use in other languages: random_praise() and  random_encouragement()

### ISSUE THREAD

**Issue by beatrizmilz** [rstudio/learnr#534]
I would like to thank the RStudio team for the efforts made to allow the use of {learnr} for different languages.

I would like to suggest that the following functions could also be used in other languages: `random_praise()` and  `random_encouragement()`.  Maybe with an argument that the default is English (something like `language="en"`) but could be possible to use praises and encouragements in other languages aswell (I know the Latin American community has been using this package a lot, creating tutorials in Spanish, specially @yabellini :) ). 

Context: I'm developing some learnr tutorials in Brazilian Portuguese.  I'm using the package gradethis, and for now we forked gradethis and translated the messages to Portuguese. gradethis uses this two functions from learnr to write the praises and encouragements. Seems like it would be nice if we could have some praises and encouragements in different languages so more people could benefit from it. 

https://github.com/rstudio/learnr/blob/master/R/praise.R
https://github.com/rstudio/learnr/blob/dd9f145f7a9453644615e7844dbeaae5e46cdfc7/R/praise.R#L64-L71

**Comment by gadenbuie** [comment]
Thanks @beatrizmilz, I think translating the encouragement and praise phrases (or providing a custom list) would be a great feature. Some thoughts:

1. We could let users set phrases via options
2. We could let users contribute translations using the existing i18n infrastructure
3. We could establish a list of phrases stored next to but separate from the existing i18n infra

I would also love to support better API for exercise feedback with gradethis and supporting translations for the random phrases would be a start in that direction.

**Comment by yabellini** [comment]
Count on me for the Spanish, I like options 1 and 3.

**Comment by schloerke** [comment]
Would it be possible to store it in the same data-raw file as the i18n information even though it is used on the R side? (Option 2) 

If it there are more fields than "generic praise" / "generic encouragement", then maybe a new data-raw file might be cleaner. (Option 3)

I also like being able to set an option to overwrite the phrases. (Option 1)

**Comment by beatrizmilz** [comment]
First of all, thank you @gadenbuie for supporting the idea, and @yabellini and @schloerke for contributing with the discussion!


From what I understood from the i18n infra that {learnr} uses, we would need to translate the available encouragement/praises from English to other languages, right?

I think it would be better if there is a list of praises and encouragements for each language, not really a direct translation of the English phrases. If someone wants to contribute just with a few phrases, so that would be enough to use with other languages.

So I also like option 3. I also think is a nice idea to have option 1 as well, if it's possible.

**Comment by gadenbuie** [comment]
Thank you again @beatrizmilz for the suggestion and to @yabellini for the discussion about providing encouragement/praise in other languages. This is now possible in learnr!

There are two options: if you would like, you may contribute random praising and encouraging phrases by updating the YAML file [data-raw/i18n_random-phrases.yml](https://github.com/rstudio/learnr/blob/master/data-raw/i18n_random-phrases.yml). You do not need to provide direct translations, but you can use the English version for inspiration.

The alternative option is to add random phrases locally to a tutorial, without needing to contribute them to the learnr package (although we'd be happy if you did!). These phrases are _added_ to existing phrases, if any are available. You can call `random_phrases_add()` in a standard R chunk or in your setup chunk (either will work).

````
```{r setup-phrases, echo = FALSE}
random_phrases_add(
  language = "en",
  praise = c("Great work!", "You're awesome!"),
  encouragement = c("I believe in you.", "Yes we can!")
)
```
````

**Comment by yabellini** [comment]
I did this PR with spanish translations: https://github.com/rstudio/learnr/pull/546
