### ISSUE TITLE
Add markdown output to answers 🙏 

### ISSUE THREAD

**Issue by MayaGans** [rstudio/learnr#535]
Hey learnr team!

We had a neat feature idea that I must admit I am naïve in how difficult it would be to implement but it'd be rad if the `answer`  function could take on a markdown snippet as an argument. 

For instance, we'd love to be able to test if the user can "translate" code:

# Example:

Which of the following would be equal to `data.frame(a = 1, b = 2)`?
-  | a | b |
   | -| -|
   |1|2|

-  | 1 | 2 |
   | -| -|
   |a|b|

**Here's some pseudo code of what I envision that could kinda look like in learnr-land**

````
---
title: "Markdown Answers"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
```


```{r letter-a, echo=FALSE}
question("Which of the following would be equal to `data.frame(a = 1, b = 2)`",
  answer(md(
    "|a|b|
    |-|-|
    |1|2|"
  ), correct = TRUE),
  answer(md(
    "|1|2|
    |-|-|
    |a|b|"
  )),
)
```
````

Any help or tips to achieve this appreciated, especially since I could see this being a cool feature for others!

**Comment by gadenbuie** [comment]
Hi @MayaGans! I'm happy to share the good news that this is already possible in learnr 😄. `learnr::answer()` turns the renders the input text as markdown by default, so you can use markdown in the answer text. The problem you're running into here is that the variant of markdown used is [commonmark](https://spec.commonmark.org/0.29/), which doesn't implement markdown tables.

Instead, you need to provide HTML tables, which can be done with `knitr::kable()`. Here's how that looks:

![image](https://user-images.githubusercontent.com/5420529/121087667-bafa3d00-c7b2-11eb-80b5-c03cf3ce51d0.png)

<details><summary>Tutorial Rmd</summary>

````
---
title: "Markdown Answers"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(learnr)
as_html_table <- function(x, ...) {
  knitr::kable(x, format = "html", table.attr = 'class="table"', ...)
}
```

# Markdown Answers

```{r letter-a, echo=FALSE}
question("Which of the following would be equal to `data.frame(a = 1, b = 2)`?",
  answer(as_html_table(data.frame(a = 1, b = 2)), correct = TRUE),
  answer(as_html_table(data.frame(`1` = "a", `2` = "b", check.names = FALSE)))
)
```

````

</details>

**Comment by MayaGans** [comment]
omg love asking a low ball thanks @gadenbuie !!!!
