### ISSUE TITLE
Prepend Feedback

### ISSUE THREAD

**Issue by markwsac** [rstudio/learnr#555]
Thanks for this useful package. I want to prepend feedback. I found feedback function in the source code but couldn't find it how to implement. Currently I am using :
`tutorial_options(exercise.checker = gradethis::grade_learnr)`

**Comment by gadenbuie** [comment]
This isn't configurable via a global option, but if you're using `gradethis` you may choose the location of the feedback by providing a `location` argument to any `pass()`, `fail()` or other grade-creation function. The `location` argument can be one of three values: `"append"`, `"prepend"`, or `"replace"`.

````
```{r example, exercise = TRUE)
1 + 1
```

```{r example-check}
grade_this({
  if (.result > 2) {
    fail("Too high!", location = "prepend")
  }
  if (.result < 2) {
    fail("Too low!", location = "replace")
  }
  pass("Good work!")
})
```
````
