### ISSUE TITLE
Cannot run tutorials

### ISSUE THREAD

**Issue by psads-git** [rstudio/learnr#559]
I have just tried the code:

`learnr::run_tutorial("hello", package = "learnr")`

but with no success:

```
Error in shiny_prerendered_prerender(input_rmd, rendered_html, output_dir,  : 
  Unable to write prerendered HTML file to /usr/lib64/R/library/learnr/tutorials/hello/hello.html

```
Thanks in advance!

**Comment by gadenbuie** [comment]
Can you please confirm that you're using the latest version of `learnr` installed from GitHub? It looks like you don't have write permissions in `/usr/lib64/R/library/learnr/tutorials`, but the latest version of `learnr` will check for write permissions and will use a temporary directory instead. If you do have the latest version of `learnr`, please copy the output of run `devtools::session_info("learnr")` and copy and paste the results into a comment here so we can investigate further.

**Comment by psads-git** [comment]
Thanks, Garrick, with the GitHub version, everything works fine!
