### ISSUE TITLE
Rerunning tutorial inside R package enables code evaluation for hints.

### ISSUE THREAD

**Issue by ddauber** [rstudio/learnr#606]
# Problem
I created a package, which includes functions, datasets and tutorials. The latter works when starting a **new R session** and running a tutorial for the **first time**.
After closing the tutorial (clicking the `stop` button) and restarting it again, all code chunks which contain hints are now evaluated and throw errors, for example, the following code chunk:

> \```{r take-sqrt-hint-2}
> sqrt(...)
> \```

results in the following error message:

> **Error in eval(expr, envir, enclos) : '...' used in an incorrect context**

Restarting the R session and running the tutorial enables the tutorial. Stopping it and rerunning it seems to allow code chunk evaluation for hints again and breaks the tutorial.

This seems to be only a problem when tutorials are in packages and using the following to load them:

```r
learnr::run_tutorial("tutorial_name", package="pkg_name")
```

Once I close the browser, the console still shows that it is listening to the IP address where the tutorial ran. Not sure why it keeps on running, but I assume it does not detect that I closed the tutorial? This likely explains this odd behaviour.

# Current Fix
I added `eval=FALSE` to all code chunks, which are hints. This solves the problem.

Thanks in advance for any help with this. I assume there must be a more straightforward fix to this than what I currently do. In my case, hints are hardly ever 'full' code that can be run but progressively builds up to the final solution.

**Comment by ddauber** [comment]
It seems the problem also applies to code chunks with `exercise=TRUE`. So they seem to be pre-evaluated by default?

**Comment by gadenbuie** [comment]
Thanks for the very detailed report. Can you please confirm that you are using the latest version of learnr from this repo? This sounds a lot like an issue that was recently fixed.

**Comment by ddauber** [comment]
I used the CRAN version because this is what my students use at the moment. I am on `learnr 0.10.1`, which is not the latest developer version: `0.10.1.9016`.

I should have spotted that. Thanks for making me aware of it. I will have to ask my students to install the developer version for now to ensure smooth study experiences.

I tested it with the developer version and there were no further errors. Thanks again for the swift reply.

**Comment by ddauber** [comment]
Thanks, @gadenbuie.

That is helpful to know. Since I will likely end up with about 100 exercises, I better get it right from the beginning. 

I am looking forward to seeing future developments of this package. It is a massive leap forward to making R more accessible to beginners.

😉
