### ISSUE TITLE
CRAN release status check

### ISSUE THREAD

**Issue by jjallaire** [rstudio/learnr#61]
@garrettgman @dtkaplan @mine-cetinkaya-rundel 

I think we've made all the changes and fixes we need to for a CRAN release. I'll let things be for 7-10 days before submitting to CRAN, in the meantime do let me know if you see anything awry or think of anything that is a must do before we go to CRAN.

**Comment by bradleyboehmke** [comment]
@jjallaire Is there a planned release date for this package to CRAN?  Just curious as I plan to use it for some upcoming short courses and want to use the most stable install instructions (i.e. the package name on Github has changed from `tutor` to `rtutor` to `learnr`).

This is a great package...thanks for all the great stuff RStudio does!

**Comment by jjallaire** [comment]
It's going to go to CRAN soon (probably next week). We don't plan on any
more name changes!

**Comment by bradleyboehmke** [comment]
Awesome...thanks!
