### ISSUE TITLE
install_github("rstudio/tutor") fails with unzip error under Windows

### ISSUE THREAD

**Issue by alex23lemm** [rstudio/learnr#64]
Yesterday, I let several people install the `tutor` package using `devtools`. All Mac and Linux users had no issues and also the installation for the majority of the Windows users went well. 

However, some of the Windows users ran into the problem described below (I provided two issue instances from two different users)
 ```r
> devtools::install_github("rstudio/tutor")
Downloading GitHub repo rstudio/tutor@master
from URL https://api.github.com/repos/rstudio/tutor/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/mshumper/AppData/Local/Temp/RtmpeE4D2Q/devtools23e061002ad9/rstudio-tutor-1476bf6/R/ace.R': No such file or directory
```
 ```r
> devtools::install_github("rstudio/tutor")
Downloading GitHub repo rstudio/tutor@master
from URL https://api.github.com/repos/rstudio/tutor/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/rb/AppData/Local/Temp/Rtmp0IlE0s/devtools416c5fc15dec/rstudio-tutor-ee380df/R/ace.R': No such file or directory
```

All users installed the current R version 3.3.3 and the current RStudio version 1.0.136  yesterday prior to trying to install `tutor` via `devtools`.

Even though I am on Windows 7 Enterprise using the same build like them I was not able to reproduce the bug on my machine.

The following two links suggest that this might be a new bug in the devtools package which also occurs when trying to install other packages using `install_github()`
http://stackoverflow.com/questions/41293748/unzip-fails-using-install-github
http://r.789695.n4.nabble.com/install-problem-from-Github-or-downloaded-file-td4729304.html#a4729306

However, I also found the following GitHub issue from 2015/16 with the same issue description as mine where the package maintainer modified  the package to fix the Windows installation problem:
https://github.com/vanatteveldt/rsyntax/issues/1

Currently, I am stuck because I am not able to reproduce the issue myself. Any advise would be highly appreciated.

**Comment by jjallaire** [comment]
Bummer, I can't get this repro either!

Can they install any packages using `devtools::install_github`?

@kevinushey Have you ever seen anything like this w/ devtools?

What if you fork the package and then rename the "ace.R" file? What if you change it's contents to remove the leading comment?

BTW the "tutor" package just got renamed "rtutor" so you'll want to update your tutorials/instructions accordingly.

**Comment by kevinushey** [comment]
FWIW my first attempt to install `rtutor` with `devtools::install_github()` on my Windows VM actually failed to download a whole bunch of recursive dependencies and so I had to install them all one-by-one. :/

**Comment by kevinushey** [comment]
After that, things install fine for me on my Windows VM as well:

```
> devtools::install_github("rstudio/rtutor")
Downloading GitHub repo rstudio/rtutor@master
from URL https://api.github.com/repos/rstudio/rtutor/zipball/master
Installing rtutor
"C:/R/R-33~1.3/bin/x64/R" --no-site-file --no-environ --no-save --no-restore --quiet CMD INSTALL  \
  "C:/Users/kevin/AppData/Local/Temp/RtmpQt7C50/devtools11605ba21507/rstudio-rtutor-a2c82ff"  \
  --library="C:/Users/kevin/Documents/R/win-library/3.3" --with-keep.source --install-tests 

* installing *source* package 'rtutor' ...
** R
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
*** arch - i386
*** arch - x64
* DONE (rtutor)
```

**Comment by jjallaire** [comment]
Me too! (on failing to download the recursive dependencies). I wonder if
that is a bug in devtools?

**Comment by alex23lemm** [comment]
Hi @jjallaire and @kevinushey,
many thanks for the quick reply. Tomorrow I will try to get the answers to jj's questions above by doing the suggested tests with one of the affected users.

And yes, also on my side devtools was not able to take care of the `rtutor` dependencies. (I forgot this to mention earlier) Therefore, the respective part of my setup script looks like this:
```r
install.packages(c("backports", "httpuv", "xtable"))
devtools::install_github("rstudio/rtutor")
```

**Comment by jjallaire** [comment]
For devtools not being able to install all the dependencies I've logged a separate bug here: https://github.com/hadley/devtools/issues/1492

**Comment by alex23lemm** [comment]
Hi @jjallaire,
As you suggested I did the following tests with two of the affected Windows users:

I forked the repo and renamed `ace.R` to `util.R`. Then I asked them to install the repo from my account:
 ```r
> devtools::install_github("alex23lemm/rtutor")
Downloading GitHub repo alex23lemm/rtutor@master
from URL https://api.github.com/repos/alex23lemm/rtutor/zipball/master
Error in utils::unzip(src, exdir = target) : 
  cannot open file 'C:/Users/amag/AppData/Local/Temp/RtmpyqLSmb/devtools4b0c5ea14107/alex23lemm-rtutor-01e935c/R/evaluators.R': No such file or directory
```
As you can see the issue continues to persist. Now, `evaluators.R` is just the first file in the `/R` folder and as a consequence generates the issue message.. Removing the leading comment also had not effects.

However, the download in general (from the rstudio repo and from my forked one) works fine since `alex23lemm-rtutor-01e935c.zip` could be found in the users temp directory structure. 

We used the following workaround to complete the installation of the package on their machines:
* They moved `rstudio-rtutor-[temp_ID]` to their project's wd and unzipped the file
* Afterwards, they installed the package using `devtools::install("rstudio-rtutor-[temp_ID]")`

Unfortunately, I forgot to ask them to download another package using `devtools::install_github()`. I will let them test this on Monday morning. 

Still a strange issue since all users (coming from the same organization) have the same Windows build and most of them have the same laptops.  I'll send you another update after we will have tested `install_gitbub()` with additional packages.

**Comment by jjallaire** [comment]
Thanks for doing that test!

How about installing other repos from GitHub? (just want to rule out that
it's not a general problem with install_github / unzipping rather than
something idiosyncratic to rtutor.

Note that the issue of all the dependencies not being installed by
install_github was confirmed as a known issue for the current version of
devtools on Windows so hopefully a fix will be forthcoming soon.

**Comment by kevinushey** [comment]
The other thing worth trying -- you could try debugging the call to `utils::unzip`, e.g.

```
debug(utils::unzip)
devtools::install_github("rstudio/rtutor")
```

After doing this, you should be able to find the path to the downloaded zipfile with e.g.

```
Browse[2]> zipfile
[1] "C:\\Users\\kevin\\AppData\\Local\\Temp\\Rtmpiggl1u\\file154c22a23bc9.zip"
```

Then, you could try navigating to that directory in e.g. the Windows explorer, and manually opening that zipfile -- does it contain all the expected contents? (I'm wondering if somehow the download is failing; e.g. the zipfile is not being downloaded completely and so some files are left out).

I believe `devtools` uses the `httr` and `curl` packages for downloading packages, so you might also want to try re-installing those just in case:

```
install.packages(c("httr", "curl"))
```

**Comment by alex23lemm** [comment]
Hi JJ and Kevin,

> How about installing other repos from GitHub? (just want to rule out that
it's not a general problem with install_github / unzipping rather than
something idiosyncratic to rtutor.

I can definitely confirm that it is a `devtools` issue under Windows. I asked several people to install other packages like, for instance, `tidyr` via `devtools::install_github("tidyverse/tidyr")` and those who failed to download `rtutor` before also failed to install other R packages hosted on GitHub with the same issue message

> I believe devtools uses the httr and curl packages for downloading packages, so you might also want to try re-installing those just in case

Re-installing them prior to trying to download `rtotor` via `install_github()` resulted in the same issue.

> (I'm wondering if somehow the download is failing; e.g. the zipfile is not being downloaded completely and so some files are left out).

Well, I did not debug `utils::unzip` on one of the affected machines but I can confirm that the download is complete as explained above. Our workaround is to unzip to downloaded zip file and then use `devtools::install("rstudio-rtutor-[temp_ID]")` to install `rtutor`. 

In regards to `rtutor` and failing Windows installations, I think the quickest solution would be to put it on CRAN to be independent from `devtools`. In our case we will continue using the installation workaround from above until the `devtools` issue is fixed or  `rtutor` is published to CRAN.

Many thanks for your support and the quick feedback.

**Comment by jjallaire** [comment]
Yes, we plan on publishing to CRAN soon however we need to wait until the
next release of rmarkdown (a couple weeks off) to pick up a critical fix
(devtools::install_github allows us to automatically get this fix on
install).

**Comment by schloerke** [comment]
Closing as I don't believe this is an issue anymore
