### ISSUE TITLE
theme change makes exercises disappear

### ISSUE THREAD

**Issue by LaurenDahlin** [rstudio/learnr#65]
Using the default tutor template (the one with the addition exercise), I can't figure out how to correctly change the theme or maybe there's a bug? When I change the params to:
```
---
title: "Tutorial" 
output: 
  rtutor::tutorial: 
    theme: "simplex" 
runtime: shiny_prerendered 
---
```

The colors change, but then the exercise boxes disappear. Am I doing something wrong?

**Comment by jjallaire** [comment]
I'm not able to reproduce this problem (tried on both Windows and Mac). What platform are you running on and what versions of packages are you using? (you can obtain the latter by executing `sessionInfo()`

**Comment by LaurenDahlin** [comment]
Sigh. Sorry you can close this issue. My problem is that if I use `rmarkdown::run(myapp.Rmd)` more than once in a session, I lose all the rtutor exercise boxes. I have no idea why this is. I have tried disabling caching and clearing my browser cache. The only way I can make everything run again is by restarting RStudio. Do you know why this is? I am running Windows 7 and Google Chrome with the latest version of RStudio.

**Comment by jjallaire** [comment]
Interesting! I'm not able to repro that issue either (using the tutorial generated by the default R Markdown template) . If you send me a minimal Rmd that you see this behavior with on your end I can try to reproduce with that.

**Comment by LaurenDahlin** [comment]
It happens when I use the default template with a theme. First time I do `rmarkdown::run("Untitled.Rmd")` it works. Then I hit stop and retry `rmarkdown::run("Untitled.Rmd")` and the boxes don't show up. I'm getting this on a Windows 7 and a Windows 10 machine using Google Chrome.

```
---
title: "Tutorial"
output: 
  rtutor::tutorial:
    theme: simplex
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(rtutor)
knitr::opts_chunk$set(echo = FALSE)
```


## Topic 1

### Exercise 

*Here's a simple exercise with an empty code chunk provided for entering the answer.*

Write the R code required to add two plus two:

```{r two-plus-two, exercise=TRUE}

```

### Exercise with Code

*Here's an exercise with some prepopulated code as well as `exercise.lines = 5` to provide a bit more initial room to work.*

Now write a function that adds any two numbers and then call it:

```{r add-function, exercise=TRUE, exercise.lines = 5}
add <- function() {
  
}
```

## Topic 2

### Exercise with Hint

*Here's an exercise where the chunk is pre-evaulated via the `exercise.eval` option (so the user can see the default output we'd like them to customize). We also add a "hint" to the correct solution via the chunk immediate below labeled `print-limit-hint`.*

Modify the following code to limit the number of rows printed to 5:

```{r print-limit, exercise=TRUE, exercise.eval=TRUE}
mtcars
```

```{r print-limit-hint}
head(mtcars)
```

### Quiz

*You can include any number of single or multiple choice questions as a quiz. Use the `question` function to define a question and the `quiz` function for grouping multiple questions together.*

Some questions to verify that you understand the purposes of various base and recommended R packages:

```{r quiz}
quiz(
  question("Which package contains functions for installing other R packages?",
    answer("base"),
    answer("tools"),
    answer("utils", correct = TRUE),
    answer("codetools")
  ),
  question("Which of the R packages listed below are used to create plots?",
    answer("lattice", correct = TRUE),
    answer("tools"),
    answer("stats"),
    answer("grid", correct = TRUE)
  )
)
```
```

**Comment by jjallaire** [comment]
Okay, I can't reproduce with the exact same conditions on Windows 10.

It seems likely that there is an error getting thrown somewhere in JavaScript land. Could you open up Chrome Developer Tools and see what errors if any show up in the console?

**Comment by LaurenDahlin** [comment]
Sorry for the silence over the weekend. It's interesting. I've now replicated the issue on two of my colleague's computers so I feel pretty confident it's not my setup. When you enter `rmardown::run(myfile.Rmd)` more than once in the console, the exercise boxes disappear, even if you haven't done any exercises.

However, when you use the button "Run Document" in R Studio, the problem does not occur. This is pretty bizarre because according to the console the Run Document button should be issuing the same command `rmardown::run(myfile.Rmd)`.

As for inspecting the JS, there are no errors in the console. The output from the hint shows up rather than the exercise entry box.

**Comment by jjallaire** [comment]
Maddening that we can't get to the bottom of this more easily! 

The fact that it works for "Run Document" isn't a big mystery as that command will always create a brand new R session to run the tutorial within (thus averting the problem).

I'm traveling this week so may not be able to dig further until next week when I get back. Will definitely try to run this down ASAP as we are nearing release to CRAN.

**Comment by jjallaire** [comment]
I think it would be valuable to capture more details on your configuration:

1. A call to `sessionInfo()` indicating the version of the packages in play.

2. Which browser are you seeing this behavior in?

3. A screenshot of exactly what you see when things "work" (Run Document) and when things don't work (run from console a second time).

Thanks!
