### ISSUE TITLE
In question(), random_answer_order = TRUE reorders too often

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#68]
If `allow_retry` is set to `TRUE`, then `random_answer_order = TRUE` will reorder the answers each time the student retries the question, which is disorienting. It tends to happen when the student is struggling to answer the question correctly.

Ideally, `random_answer_order = TRUE` would order the answers randomly when the question first appears, and then the answers would stay put.

You can test the behavior with the below:

````
---
title: "Tutorial"
output: rtutor::tutorial
runtime: shiny_prerendered
---

```{r setup, include=FALSE}
library(rtutor)
```

## Topic 1

### Exercise 

```{r quiz, echo = FALSE}
question("How many sides does a triangle have?",
  answer("1"),
  answer("2"),
  answer("3", correct = TRUE),
  answer("4"),
  answer("5"),
  allow_retry = TRUE,
  random_answer_order = TRUE
)
```
````

**Comment by jjallaire** [comment]
It will be tricky to make them random at first and then preserve the order for retries. 

We could make `random_answer_order` unavailable when `allow_retry = TRUE`, however that seems a bit restrictive especially when there is a workaround (don't use `random_answer_order` if you don't like it). 

I think we should leave this as is for now.

**Comment by jjallaire** [comment]
My comment about it being restrictive is that some instructors might like the re-ordering (makes the user consider all the answers anew each time).

It would be in theory be possible to get the behavior you are seeking but it would involve hacking around some limitations of the quiz library we are using, so not worth the cost IMO.

**Comment by jjallaire** [comment]
Re-opened just so we consider this next time we do a pass through the issues.

**Comment by garrettgman** [comment]
That makes sense about the cost benefit ratio. 

One reason I brought it up, is as a question writer, I was cued to see `random_answer_order` as a solution to a problem that I faced: my tendency to put the correct answer in the same spot over time. It didn't occur to me that `random_answer_order` existed for another reason (e.g  to reorder the answers on each retry, which I'm still skeptical of )

**Comment by mine-cetinkaya-rundel** [comment]
I believe it's common to reorder answers on each try on online quiz platforms. While this can be frustrating for the student who is truly trying but struggling to get the right answer, it can also serve to make the student who is mindlessly trying out all choices to stop and think. So I definitely see benefits to both approaches from a pedagogical perspective.

**Comment by garrettgman** [comment]
Ah, that makes sense @mine-cetinkaya-rundel. Thanks for helping me see it that way. I think I would personally use the case where the answers appear randomized the first time and then never change most often, but I can see the purpose of what you describe (and we have).

**Comment by gadenbuie** [comment]
Answers are now only randomized on session start.
