### ISSUE TITLE
Height of the hint box is 1 line only

### ISSUE THREAD

**Issue by cswclui** [rstudio/learnr#689]
I am using the latest version of learnr (Version ‘0.10.1.9022’). The following is a test Rmd document.

<pre>
---
title: "Test"
output: 
  learnr::tutorial:
    progressive: true
runtime: shiny_prerendered
---

# Test

This is a demo which shows that the height of the hint box is one line only.

```{r demo, exercise = TRUE}
1+1
```

```{r demo-hint}
line1
line2
line3
```

</pre>

The height of the hint box is only showing 1 line (refer to the screen capture below). Similarly, the solution box is also 1 line only even there are multiple lines in the hint/solution.

![image](https://user-images.githubusercontent.com/218137/166970518-bc698afa-2387-46e5-afb1-5bc31b4b5665.png)

Is there any fix for that?

Thank you.

**Comment by cswclui** [comment]
It seems it's the bug related to the latest version of learnr. As I am also using gradethis (which use the latest version of learnr), I have to install the older version
```
install_version("learnr", version = "0.10.1", repos = "http://cran.us.r-project.org")
devtools::install_github("rstudio/gradethis@0f87ab5db1d90e09f2e23ca4383555b4d94e1559")
```

**Comment by gadenbuie** [comment]
Thank for the report! I can reproduce the bug on my end and I've tracked down the source of the issue. If all goes well, I have a fix in for this tomorrow 😄

**Comment by gadenbuie** [comment]
Hi @cswclui, I just pushed a fix for the hint/solution popover height. It should be working as expected now if you install the latest version of learnr from GitHub (but please let me know if you run into any more issues with this!).

```
devtools::install_github("rstudio/learnr")
```

**Comment by cswclui** [comment]
Thanks. The problem is now fixed.
