### ISSUE TITLE
Tutorial is non-responsive if the next hint is clicked at the last hint

### ISSUE THREAD

**Issue by cswclui** [rstudio/learnr#694]
For multi-step hints, the `Next Hint` button can be clicked at the last hint (the button is greyed but it can be clicked). The `Start Over` and `Run Code` button becomes non-responsive after.

Example learnr tutorial:
<pre>
# Test

```{r demo, exercise = TRUE}
1+1
```

```{r demo-hint-1, eval=FALSE}
hint1
```

```{r demo-hint-2, eval=FALSE}
hint2
```

</pre>

![image](https://user-images.githubusercontent.com/218137/168447677-955b0901-09eb-42c2-b3ba-d3139fddcf85.png)

**Comment by gadenbuie** [comment]
Thanks for the bug report! This should be fixed now 😄
