### ISSUE TITLE
Custom question does not work as expected

### ISSUE THREAD

**Issue by dmenne** [rstudio/learnr#722]
This is a repost of https://github.com/rstudio/learnr/issues/720 which was closed after another issue was resolved.

The custom example does not work as expected, because `question_is_correct.always_correct` is never called.
When I change the type to `type = c("always_correct")` , I would expect an error telling me that one of the non-implemented custom versions is not available. However, the warning is

```
Error in : `question_is_correct.always_correct(question, ...)` has not been implemented
```
which is not correct because this function IS implemented. Some namespacing problem?

![2022-08-04 10_45_45-How to use shiny](https://user-images.githubusercontent.com/506275/182819251-80fe3302-b784-4edc-baf4-4d53e58c4663.png)

````
---
title: "How to use shiny"
output: learnr::tutorial
runtime: shiny_prerendered
---

```{r context="setup", include=FALSE}
library(learnr)

```

## Topic 1

### Using Shiny

```{r custom_class, echo = FALSE}
question_is_correct.always_correct <- function(question, value, ...) {
  return(learnr::mark_as(TRUE, message = NULL))
}

ques <- question(
  "Custom Method",
  answer("answer", correct = TRUE),
  answer("also marked as correct", correct = FALSE),
  type = c("always_correct", "learnr_checkbox")
)
ques
```
````

**Comment by gadenbuie** [comment]
I'm not exactly sure why but R isn't finding the `always_correct` S3 method. It does work if you explicitly register the S3 method, though:

```r
registerS3method(
  genname = "question_is_correct", 
  class = "always_correct",
  method = function(question, value, ...) {
    learnr::mark_as(TRUE, messages = NULL)
  }
)
```

I'll update the docs shortly. Note that if you're creating your custom question in a package, you don't need to use the above, you'd instead use the `@export` roxygen2 directive to ensure that the method is correctly registered:

```r
#' @export
question_is_correct.always_correct <- function(question, value, ...) {
  return(learnr::mark_as(TRUE, messages = NULL))
}
```

**Comment by dmenne** [comment]
https://developer.r-project.org/Blog/public/2019/08/19/s3-method-lookup/
https://stackoverflow.com/a/66831719/229794

**Comment by dmenne** [comment]
Alternative (somewhat easier to read, I believe)

```
question_is_correct.always_correct = function(question, value, ...) {
    learnr::mark_as(TRUE, messages = NULL)
}

.S3method("question_is_correct", "always_correct")

**Comment by gadenbuie** [comment]
Yeah, but beware that `.S3method` implicitly requires R >= 4.0.0 since it isn't available in any 3.x version of R.
