### ISSUE TITLE
Code in global setup chunk cannot be referenced under Windows

### ISSUE THREAD

**Issue by alex23lemm** [rstudio/learnr#73]
It seems that code added to the global setup chunk cannot be referenced under Windows.
Here is a small reproducible example:

    ---
    title: "Tutorial"
    output: learnr::tutorial
    runtime: shiny_prerendered
    ---

    ```{r setup, include=FALSE}
    library(learnr)
    nycflights <- nycflights13::flights
    ```

    ```{r filter, exercise=TRUE}
    # Change the filter to select February rather than January
    dplyr::filter(nycflights, month == 1)
    ```
The code above leads to a "Object 'nycflights' not found" error:

![global_setup_chunk_issue](https://cloud.githubusercontent.com/assets/611112/26080764/4c54b6f4-39c8-11e7-9c67-349004a55a5e.jpg)

Here is my respective session info:
> devtools::session_info()
Session info ----------------------------------------------------------------------------------
 setting  value                       
 version  R version 3.4.0 (2017-04-21)
 system   x86_64, mingw32             
 ui       RStudio (1.0.136)           
 language (EN)                        
 collate  German_Germany.1252         
 tz       Europe/Berlin               
 date     2017-05-15                  
Packages --------------------------------------------------------------------------------------
 package     * version date       source        
 backports     1.0.5   2017-01-18 CRAN (R 3.4.0)
 base        * 3.4.0   2017-04-21 local         
 compiler      3.4.0   2017-04-21 local         
 datasets    * 3.4.0   2017-04-21 local         
 devtools      1.13.1  2017-05-13 CRAN (R 3.4.0)
 digest        0.6.12  2017-01-27 CRAN (R 3.4.0)
 evaluate      0.10    2016-10-11 CRAN (R 3.4.0)
 graphics    * 3.4.0   2017-04-21 local         
 grDevices   * 3.4.0   2017-04-21 local         
 htmltools     0.3.6   2017-04-28 CRAN (R 3.4.0)
 htmlwidgets   0.8     2016-11-09 CRAN (R 3.4.0)
 httpuv        1.3.3   2015-08-04 CRAN (R 3.4.0)
 jsonlite      1.4     2017-04-08 CRAN (R 3.4.0)
 knitr         1.15.1  2016-11-22 CRAN (R 3.4.0)
 learnr        0.8     2017-05-08 CRAN (R 3.4.0)
 magrittr      1.5     2014-11-22 CRAN (R 3.4.0)
 markdown      0.8     2017-04-20 CRAN (R 3.4.0)
 memoise       1.1.0   2017-04-21 CRAN (R 3.4.0)
 methods     * 3.4.0   2017-04-21 local         
 mime          0.5     2016-07-07 CRAN (R 3.4.0)
 R6            2.2.1   2017-05-10 CRAN (R 3.4.0)
 Rcpp          0.12.10 2017-03-19 CRAN (R 3.4.0)
 rmarkdown     1.5     2017-04-26 CRAN (R 3.4.0)
 rprojroot     1.2     2017-01-16 CRAN (R 3.4.0)
 shiny         1.0.3   2017-04-26 CRAN (R 3.4.0)
 stats       * 3.4.0   2017-04-21 local         
 stringi       1.1.5   2017-04-07 CRAN (R 3.4.0)
 stringr       1.2.0   2017-02-18 CRAN (R 3.4.0)
 tools         3.4.0   2017-04-21 local         
 utils       * 3.4.0   2017-04-21 local         
 withr         1.0.2   2016-06-20 CRAN (R 3.4.0)
 xtable        1.8-2   2016-02-05 CRAN (R 3.4.0)
 yaml          2.1.14  2016-11-12 CRAN (R 3.4.0)

My current workaround to make code available globally in all chunks is to put everything in `global.R` which is then sourced in the global setup chunk:

    ```{r setup, include=FALSE}
    library(learnr)
    source("global.r")
    ```

**Comment by jjallaire** [comment]
Yikes! I'll take a look at fixing that ASAP.

**Comment by jjallaire** [comment]
Fixed here: https://github.com/rstudio/learnr/commit/db46127a3216db096d1f3b7648afdbee11f1953e

**Comment by jjallaire** [comment]
This now works but I'm not sure we are executing in exactly the environment we want to.

**Comment by alex23lemm** [comment]
I can confirm that this now works in general but I think that one thing could be improved:

 If you define variables or functions in the global setup chunk now, `ls()` won't show them when being executed in an exercise chunk. Instead it returns `character(0)` even though the objects are there. You just need to know their names in order to use them.

However, if you define objects in setup chunks (not the global one)  which are shared by several exercises further downstream, `ls()` shows those objects when being executed in the downstream exercises. This should be the correct behavior.

**Comment by jjallaire** [comment]
One issue this would present is that it might require copying all of the objects from the setup environment to the exercise environment (whether a copy is actually made depends on how R handles reference counting). My guess is that these copies would tend to be pretty cheap but it's important to keep in mind that if you put something very large in the setup chunk it will slow down exercise execution.

**Comment by jjallaire** [comment]
Okay, I've implemented this here: https://github.com/rstudio/learnr/commit/9427612250b3e3df86c45622d61d26e892dc3f93

`ls()` now includes all objects defined in the setup and data chunks.
