### ISSUE TITLE
Please Update CRAN version

### ISSUE THREAD

**Issue by davidkane9** [rstudio/learnr#730]
Could you please update the CRAN version? It is no more than 2 and a half years old.

Normally, I would just install from Github, but I am dealing with a cloud installation which I do not control and for which the sys admins prefer to only install from CRAN.

Thanks!

**Comment by coatless** [comment]
@jjallaire @schloerke @gadenbuie any chance the CRAN version of `learnr` could be bumped?

Having students go the `devtools` route as the CRAN version is ~2.5 years behind is problematic when they are just learning _R_.

**Comment by jjallaire** [comment]
@gadenbuie I think you are the current maintainer --- could you submit the updated version to CRAN?

**Comment by gadenbuie** [comment]
learnr v0.11.0 is now on CRAN! Read all about the changes in [the learnr v0.11.0 release notes](https://pkgs.rstudio.com/learnr/articles/releases/learnr_v0-11-0.html).

**Comment by coatless** [comment]
@gadenbuie huzzah!
