### ISSUE TITLE
Change default error message for `question_checkbox()`

### ISSUE THREAD

**Issue by garrettgman** [rstudio/learnr#731]
Can we change the default error message for `question_checkbox()` from
- `incorrect = "Incorrect"`
to something like
- `incorrect = "Incorrect. Be sure to select every correct answer."`?

`question_checkbox()` differs from `question_radio()` in that it allows for more than one correct answer—_and students must select every correct answer to pass_.  I've noticed several students assume that a checkbox question is a radio question. They select one correct answer and receive `"Incorrect!"`. They then switch to a different correct answer and also receive `"Incorrect!"`. This creates frustration, which I think we could solve by automatically including a nudge to look for multiple correct answers.

**Caveat**: the proposed message may not play well with `allow_retry = FALSE`. I don't think that's fatal, but I'm happy to entertain better messages 😄 .

**Comment by gadenbuie** [comment]
Excellent point. It turns out that `try_again` is the best entry point for fixing this. We were showing `"Incorrect"` for both the try again message and the "final answer" message. In #732 we give the message you suggested for try again.

**Comment by garrettgman** [comment]
That is brilliant! Thanks @gadenbuie.
