### ISSUE TITLE
multiple set up chunks needed in long tutorial

### ISSUE THREAD

**Issue by LaurenDahlin** [rstudio/learnr#75]
First of all, I have to say thank you to you all for making this package. I teach 1.5-hour- to 3-day-long seminars on various topics in R and Stata and I think learnr made for the best participant experience of any session I've ever done. I am happy to report that my learnr tutorial worked flawlessly on 30 computers running various versions of RStudio and multiple operating systems.

I do want to report an issue though for you to check out. You can view my repository [here](https://github.com/strategicdataproject/dataviz-r). Sorry for lack of short reproducible example.

I need only one set up chunk where I load a short data frame. However, to get the document to run, for some reason I had to periodically repeat the same set up chunk with a new name. You'll see this in my document where I have loadData, loadData2, loadData3, etc. If you replace, for example, loadData2 with loadData as the set up chunk, the document will not run even though they are exactly the same chunk of code. I forget the exact error message. I can reproduce if you don't have time to look at my repo.

**Comment by jjallaire** [comment]
You have found a truly bizarre error condition!  So glad you were able to find a workaround (albeit a pretty inconvenient one). I'll dig into this and figure out what is going on.

Note that exercises not seeing objects defined in the global setup chunk is a separate bug that has now been fixed. Note that when you install a new version of the learnr package with a fix it's best to remove the .html files generated by your tutorial Rmd files (as they need to be rebuilt when the package is updated).

**Comment by jjallaire** [comment]
Fixed via https://github.com/rstudio/learnr/commit/35066b527acdd4a1df6f36f7c84ce62baf65b5be

**Comment by dtkaplan** [comment]
I'll confirm @LaurenDahlin problem with repeated use of the same start-up chunk in many exercises. Good news! The minimal example I constructed doesn't have that problem with today's update to `learnr`.
