### ISSUE TITLE
Flashcards

### ISSUE THREAD

**Issue by drfurtado** [rstudio/learnr#762]
I would like to suggest the creation of a function that would allow us to create flashcards that can be published and shared for studying purposes.

**Comment by gadenbuie** [comment]
This is a great idea and thank you for sharing. I have a vague recollection of a seeing a similar package that helps with this idea, but I couldn't find it with a quick search just now. 

Ultimately, I do think this would be better as a separate package than inside learnr, so I'm going to close this issue. If you do find a solution, please let us know!
