### ISSUE TITLE
Code Reset button?

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#79]
It would be nice if users could reset the code in an individual code block back to the state before they began edits without having to restart the entire tutorial.  Would this be easy to add?

**Comment by jjallaire** [comment]
Very easy! Added here: https://github.com/rstudio/learnr/commit/78c24d9904a04bda1c03fa0d28a3f05d6709581d

**Comment by rpruim** [comment]
Excellent.  I'll give it a try.

**Comment by rpruim** [comment]
Works great.  Thanks.

**Comment by rpruim** [comment]
Should "Start Over" also remove any output from the previous code?  Note in the example below that after hitting start over, the output is still displayed from the code that had been there previously.

![image](https://cloud.githubusercontent.com/assets/722231/26639002/a5f77018-45f1-11e7-9922-9c1813cab440.png)

**Comment by rpruim** [comment]
Also, attempting to run code with a blank not yet filled in should return a message to that effect rather than the R error message that is likely to occur if the code is actually run.

**Comment by jjallaire** [comment]
Unfortunately I can't do this easily because Shiny is managing the contents of output frames, and if I go behind Shiny's back and start manipulating it's output then weird side effects may ensue.

**Comment by rpruim** [comment]
Is #83 easier?

**Comment by jjallaire** [comment]
I've now got removal of all output (hints, errors, actual output, etc.) working with the start over button.
