### ISSUE TITLE
HTML table output not rendering

### ISSUE THREAD

**Issue by bradleyboehmke** [rstudio/learnr#88]
When using progressive rendering (`progressive: true`), and when I have an HTML table output produced from code such as the following in a future section,

```{r}
mtcars
```

the HTML tables often do not show up and the user is required to refresh the page.  Also, the refresh brings the user back to the top of the tutorial requiring them to scroll down to where they left off.

As an example, if you run the following:

`devtools::install_github("bradleyboehmke/learningAnalytics")`
`learningAnalytics::get_tutorial("Linear Regression")`

and work through the first few exercises until you get to the __Assessing Coefficients__ section you will notice a blank table after the `tidy(model1)` line.  If you refresh it will display properly.

I taught a short course of 18 and all 18 had this same problem throughout the tutorials.  However, note that this was the *only* complaint as everyone loved this integrated learning approach.  Definite kudos to a great package!

**Comment by jjallaire** [comment]
Thanks for the report. The best way for us to productively troubleshoot is if you provide source code for a minimal reproducible example (i.e. the smallest example Rmd where you see the problem exhibited).

**Comment by jjallaire** [comment]
@robbyshaver and @javierluraschi, this is an issue I haven't discovered the cause of whereby when using progressive reveal sometimes paged tables show up blank (they are still in the DOM but appear to have visibility:hidden). You can repro as follows:

```r
devtools::install_github("bradleyboehmke/learningAnalytics")
learningAnalytics::get_tutorial("Linear Regression")
```

Then, just click to the "Simple Linear Regression" section:
<img width="322" alt="screen shot 2017-06-09 at 8 52 43 am" src="https://user-images.githubusercontent.com/104391/26983573-1501914a-4cf1-11e7-9368-433ed9971ab1.png">

And work though the first couple of sub-topics (you can enter any R input e.g. `10` you don't need to actually provide a legit solution to the exercises!).

If you want to repro again after this you should use the "Start Over" link below the table of contents.

I think this is an issue we should address before the next CRAN release. This is some sort of interaction between paged tables and progressive reveal so might require some pooling of knowledge!

**Comment by rpruim** [comment]
Just confirming that I've seen this in the wild -- and that it seems to come and go.

**Comment by jjallaire** [comment]
@garrettgman Has also seen it

**Comment by robbyshaver** [comment]
I did the setup and can see the bug. Given that refreshing the web page causes the table to display correctly after it's been progressively revealed, I'm guessing there's some code that depends on the table being in the DOM when it executes.

Note that by editing (or removing) the following opacity style property, I can get the table to appear:

`<div class="pagedtable pagedtable-not-empty" style="opacity: 0;">`

**Comment by jjallaire** [comment]
@jcheng5 Does Shiny progress set opacity? I'm wondering if we aren't quite interacting with Shiny progress in an expected fashion here.

@javierluraschi Could you take a look at this issue? 

Here's the spot in the code where we actually ensure that paged tables are bound: https://github.com/rstudio/learnr/blob/master/inst/lib/tutorial/tutorial.js#L1333-L1335

Perhaps another bit there is required?

**Comment by javierluraschi** [comment]
@jjallaire the ideal fix is [this](https://github.com/rstudio/rmarkdown/pull/1083) `rmarkdown` PR, would it be possible to take that fix in this package? Otherwise, it should be possible to also trigger this from `learnr` during the shiny callback, I think. I can take another look if we want a fix in this package.

**Comment by jjallaire** [comment]
Thanks!!! Yes, we can take the fix in rmarkdown.
