### ISSUE TITLE
Progressive Reveal feature not working on shinyapp servers

### ISSUE THREAD

**Issue by nlhuong** [rstudio/learnr#92]
Running my Rmd locally works fine, and all exercises reveal after the previous ones are completed by a user. However, when running on a server, it seems like R doesn't recognize that the answers have been submitted/ the code has been run, and I get the following error:

"You must complete the exercise in this section before continuing."

when clicking on a Continue button. 

(I am using checkr package in the tutorial).

**Comment by jjallaire** [comment]
We just fixed a bug related to this today. Could you try
install_github("rstudio/learnr") and then redeploying to shinyapps.io to
verify that fixes the issue?

**Comment by nlhuong** [comment]
With learnr_0.8.0.9004 now everything works! Thanks!

**Comment by jjallaire** [comment]
Great, very glad to hear!!!

On Wed, Jun 14, 2017 at 10:05 PM, Lan Huong Nguyen <notifications@github.com
