### ISSUE TITLE
undesired feature: setup chunks always hidden

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#93]
It appears that if an R chunk is used with `exercise.setup`, then there is no way to make it visible.  But I would like to have some code that is visible to the user, but not editable, followed by an exercise chunk where they use that code.

In my particular use case, I want to define a function and let the user experiment with different argument values, but I don't want them to be able to break the function itself.

`echo = TRUE` seems not to work on these chunks.

**Comment by rpruim** [comment]
Here's an example demonstrating the issue:


[setup-issues.Rmd.txt](https://github.com/rstudio/learnr/files/1079366/setup-issues.Rmd.txt)

**Comment by dtkaplan** [comment]
You can get the setup chunk into the knitr content by using ref.label:

````
```{r, foo}
x <- "local"
# this will be connected to the exercise chunk using exercise.setup = "foo"
```
````
Duplicate the contents of that chunk in an ordinary chunk

````
```{r, ref.label="foo"}
```
````

**Comment by rpruim** [comment]
Indeed @dtkaplan is correct about using `ref.label` (which is what I meant to be doing, but didn't do.)  I modified my example and that works.  So at least one can get the code without having to duplicate it.  

But it still seems like `echo = TRUE` should cause the code to be echoed, but it does not.

**Comment by jjallaire** [comment]
The setup chunk is hidden due to the `include = FALSE` chunk option. Just remove that option and it will be displayed.

**Comment by rpruim** [comment]
I think this needs to be re-opened.  I'll attach an example file and a screen shot.  The issue here involves using `exercise.setup = `.  Even with an explicit `include = TRUE` it does not show up.

[setup-issues.Rmd.txt](https://github.com/rstudio/learnr/files/1082187/setup-issues.Rmd.txt)



![image](https://user-images.githubusercontent.com/722231/27248284-68650c16-52cf-11e7-84cb-323598bb89ea.png)

**Comment by jjallaire** [comment]
That's correct. Setup chunk are not intended to be user-visible (they don't
run at all during knit). They are code to run silently to prep an
environment for an exercise. So this is "by design" but as you point out it
might not be good design! I'll leave this open and revisit when we look at
enhancements again after the release.

**Comment by rpruim** [comment]
Sounds good.  Even if they default to `include = FALSE`, it seems like one should be able to `include = TRUE` and get them to appear.

**Comment by gadenbuie** [comment]
At this point I think learnr's design of excluding exercise chunks from the pre-rendered document is well-established and unlikely to change. Fortunately, you can use the `ref.label` chunk option to re-use a setup code chunk in the pre-rendered document.
