### ISSUE TITLE
Code warnings often flag legitimate code

### ISSUE THREAD

**Issue by rpruim** [rstudio/learnr#95]
I'm often seeing the code warnings even when the code is fine and runs.

"Unexpeted comma" seems to be a common complaint.

![image](https://user-images.githubusercontent.com/722231/27210608-9b2c7d9a-5221-11e7-97dc-2079ce3f252d.png)

**Comment by kevinushey** [comment]
Can you provide the snippet of code here that's generating the false positives?

**Comment by rpruim** [comment]
I did a little experimenting, and it seems to be sensitive to line breaks.  This gives the warning:

```r
GapMinderPlot(
  LifeExpectency, 
  countries = c("Germany", "United States", "New Zealand", "China", 
                 "India", "Japan"))
GapMinderPlot(LifeExpectency)
```
but 
```r
GapMinderPlot(
  LifeExpectency, 
  countries = c("Germany", "United States", "New Zealand", "China", "India", "Japan"))
GapMinderPlot(LifeExpectency)
``` 
does not.

![image](https://user-images.githubusercontent.com/722231/27226593-ce85ed38-526d-11e7-91d4-e58894f03591.png)

**Comment by jjallaire** [comment]
@kevinushey I added this an issue for the upcoming v0.9 release. If it ends up being the case that this is too tricky or risky to get right then we could turn off diagnostics by default.

**Comment by kevinushey** [comment]
I think this shouldn't be too difficult to fix -- I'll try to take a look soon.
